// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_
#define FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct SunspecPointDef;
struct SunspecPointDefBuilder;

struct SunspecGroupPointDef;
struct SunspecGroupPointDefBuilder;

struct SunspecModelDef;
struct SunspecModelDefBuilder;

enum SunspecPointAccessType : uint8_t {
  SunspecPointAccessType_kR = 0,
  SunspecPointAccessType_kRW = 1,
  SunspecPointAccessType_MIN = SunspecPointAccessType_kR,
  SunspecPointAccessType_MAX = SunspecPointAccessType_kRW
};

inline const SunspecPointAccessType (&EnumValuesSunspecPointAccessType())[2] {
  static const SunspecPointAccessType values[] = {
    SunspecPointAccessType_kR,
    SunspecPointAccessType_kRW
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointAccessType() {
  static const char * const names[3] = {
    "kR",
    "kRW",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointAccessType(SunspecPointAccessType e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointAccessType_kR, SunspecPointAccessType_kRW)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointAccessType()[index];
}

enum SunspecPointMandatoryType : uint8_t {
  SunspecPointMandatoryType_kM = 0,
  SunspecPointMandatoryType_kO = 1,
  SunspecPointMandatoryType_MIN = SunspecPointMandatoryType_kM,
  SunspecPointMandatoryType_MAX = SunspecPointMandatoryType_kO
};

inline const SunspecPointMandatoryType (&EnumValuesSunspecPointMandatoryType())[2] {
  static const SunspecPointMandatoryType values[] = {
    SunspecPointMandatoryType_kM,
    SunspecPointMandatoryType_kO
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointMandatoryType() {
  static const char * const names[3] = {
    "kM",
    "kO",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointMandatoryType(SunspecPointMandatoryType e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointMandatoryType_kM, SunspecPointMandatoryType_kO)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointMandatoryType()[index];
}

enum SunspecPointDataType : uint8_t {
  SunspecPointDataType_kUndefinedType = 0,
  SunspecPointDataType_kInt16 = 1,
  SunspecPointDataType_kInt32 = 2,
  SunspecPointDataType_kInt64 = 3,
  SunspecPointDataType_kRaw16 = 4,
  SunspecPointDataType_kUint16 = 5,
  SunspecPointDataType_kUint32 = 6,
  SunspecPointDataType_kUint64 = 7,
  SunspecPointDataType_kAcc16 = 8,
  SunspecPointDataType_KAcc32 = 9,
  SunspecPointDataType_kAcc64 = 10,
  SunspecPointDataType_kBitField16 = 11,
  SunspecPointDataType_kBitField32 = 12,
  SunspecPointDataType_kBitField64 = 13,
  SunspecPointDataType_kEnum16 = 14,
  SunspecPointDataType_kEnum32 = 15,
  SunspecPointDataType_kFloat32 = 16,
  SunspecPointDataType_kFloat64 = 17,
  SunspecPointDataType_kString = 18,
  SunspecPointDataType_kSunsSf = 19,
  SunspecPointDataType_kPad = 20,
  SunspecPointDataType_kIpAddr = 21,
  SunspecPointDataType_kIpv6Addr = 22,
  SunspecPointDataType_kEui48 = 23,
  SunspecPointDataType_MIN = SunspecPointDataType_kUndefinedType,
  SunspecPointDataType_MAX = SunspecPointDataType_kEui48
};

inline const SunspecPointDataType (&EnumValuesSunspecPointDataType())[24] {
  static const SunspecPointDataType values[] = {
    SunspecPointDataType_kUndefinedType,
    SunspecPointDataType_kInt16,
    SunspecPointDataType_kInt32,
    SunspecPointDataType_kInt64,
    SunspecPointDataType_kRaw16,
    SunspecPointDataType_kUint16,
    SunspecPointDataType_kUint32,
    SunspecPointDataType_kUint64,
    SunspecPointDataType_kAcc16,
    SunspecPointDataType_KAcc32,
    SunspecPointDataType_kAcc64,
    SunspecPointDataType_kBitField16,
    SunspecPointDataType_kBitField32,
    SunspecPointDataType_kBitField64,
    SunspecPointDataType_kEnum16,
    SunspecPointDataType_kEnum32,
    SunspecPointDataType_kFloat32,
    SunspecPointDataType_kFloat64,
    SunspecPointDataType_kString,
    SunspecPointDataType_kSunsSf,
    SunspecPointDataType_kPad,
    SunspecPointDataType_kIpAddr,
    SunspecPointDataType_kIpv6Addr,
    SunspecPointDataType_kEui48
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointDataType() {
  static const char * const names[25] = {
    "kUndefinedType",
    "kInt16",
    "kInt32",
    "kInt64",
    "kRaw16",
    "kUint16",
    "kUint32",
    "kUint64",
    "kAcc16",
    "KAcc32",
    "kAcc64",
    "kBitField16",
    "kBitField32",
    "kBitField64",
    "kEnum16",
    "kEnum32",
    "kFloat32",
    "kFloat64",
    "kString",
    "kSunsSf",
    "kPad",
    "kIpAddr",
    "kIpv6Addr",
    "kEui48",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointDataType(SunspecPointDataType e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointDataType_kUndefinedType, SunspecPointDataType_kEui48)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointDataType()[index];
}

enum SunspecGroupType : uint8_t {
  SunspecGroupType_kGroup = 0,
  SunspecGroupType_kSync = 1,
  SunspecGroupType_MIN = SunspecGroupType_kGroup,
  SunspecGroupType_MAX = SunspecGroupType_kSync
};

inline const SunspecGroupType (&EnumValuesSunspecGroupType())[2] {
  static const SunspecGroupType values[] = {
    SunspecGroupType_kGroup,
    SunspecGroupType_kSync
  };
  return values;
}

inline const char * const *EnumNamesSunspecGroupType() {
  static const char * const names[3] = {
    "kGroup",
    "kSync",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecGroupType(SunspecGroupType e) {
  if (::flatbuffers::IsOutRange(e, SunspecGroupType_kGroup, SunspecGroupType_kSync)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecGroupType()[index];
}

enum SunspecModelList : uint16_t {
  SunspecModelList_KModelInvalid = 0,
  SunspecModelList_kModel1 = 1,
  SunspecModelList_kModel101 = 101,
  SunspecModelList_kModel102 = 102,
  SunspecModelList_kModel103 = 103,
  SunspecModelList_kModel111 = 111,
  SunspecModelList_kModel112 = 112,
  SunspecModelList_kModel113 = 113,
  SunspecModelList_kModel120 = 120,
  SunspecModelList_kModel126 = 126,
  SunspecModelList_kModel160 = 160,
  SunspecModelList_kModelEnd = 65535,
  SunspecModelList_MIN = SunspecModelList_KModelInvalid,
  SunspecModelList_MAX = SunspecModelList_kModelEnd
};

inline const SunspecModelList (&EnumValuesSunspecModelList())[12] {
  static const SunspecModelList values[] = {
    SunspecModelList_KModelInvalid,
    SunspecModelList_kModel1,
    SunspecModelList_kModel101,
    SunspecModelList_kModel102,
    SunspecModelList_kModel103,
    SunspecModelList_kModel111,
    SunspecModelList_kModel112,
    SunspecModelList_kModel113,
    SunspecModelList_kModel120,
    SunspecModelList_kModel126,
    SunspecModelList_kModel160,
    SunspecModelList_kModelEnd
  };
  return values;
}

inline const char *EnumNameSunspecModelList(SunspecModelList e) {
  switch (e) {
    case SunspecModelList_KModelInvalid: return "KModelInvalid";
    case SunspecModelList_kModel1: return "kModel1";
    case SunspecModelList_kModel101: return "kModel101";
    case SunspecModelList_kModel102: return "kModel102";
    case SunspecModelList_kModel103: return "kModel103";
    case SunspecModelList_kModel111: return "kModel111";
    case SunspecModelList_kModel112: return "kModel112";
    case SunspecModelList_kModel113: return "kModel113";
    case SunspecModelList_kModel120: return "kModel120";
    case SunspecModelList_kModel126: return "kModel126";
    case SunspecModelList_kModel160: return "kModel160";
    case SunspecModelList_kModelEnd: return "kModelEnd";
    default: return "";
  }
}

struct SunspecPointDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecPointDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_COUNT = 8,
    VT_COUNT_POINT_ID = 10,
    VT_SIZE = 12,
    VT_SF = 14,
    VT_SF_ID = 16,
    VT_UNITS = 18,
    VT_ACCESS = 20,
    VT_MANDATORY = 22,
    VT_LABEL = 24
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  SunspecPointDataType type() const {
    return static_cast<SunspecPointDataType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  uint16_t count() const {
    return GetField<uint16_t>(VT_COUNT, 1);
  }
  const ::flatbuffers::String *count_point_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNT_POINT_ID);
  }
  uint16_t size() const {
    return GetField<uint16_t>(VT_SIZE, 0);
  }
  int16_t sf() const {
    return GetField<int16_t>(VT_SF, 0);
  }
  const ::flatbuffers::String *sf_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SF_ID);
  }
  const ::flatbuffers::String *units() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UNITS);
  }
  SunspecPointAccessType access() const {
    return static_cast<SunspecPointAccessType>(GetField<uint8_t>(VT_ACCESS, 0));
  }
  SunspecPointMandatoryType mandatory() const {
    return static_cast<SunspecPointMandatoryType>(GetField<uint8_t>(VT_MANDATORY, 1));
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint16_t>(verifier, VT_COUNT, 2) &&
           VerifyOffset(verifier, VT_COUNT_POINT_ID) &&
           verifier.VerifyString(count_point_id()) &&
           VerifyField<uint16_t>(verifier, VT_SIZE, 2) &&
           VerifyField<int16_t>(verifier, VT_SF, 2) &&
           VerifyOffset(verifier, VT_SF_ID) &&
           verifier.VerifyString(sf_id()) &&
           VerifyOffset(verifier, VT_UNITS) &&
           verifier.VerifyString(units()) &&
           VerifyField<uint8_t>(verifier, VT_ACCESS, 1) &&
           VerifyField<uint8_t>(verifier, VT_MANDATORY, 1) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           verifier.EndTable();
  }
};

struct SunspecPointDefBuilder {
  typedef SunspecPointDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(SunspecPointDef::VT_ID, id);
  }
  void add_type(SunspecPointDataType type) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_count(uint16_t count) {
    fbb_.AddElement<uint16_t>(SunspecPointDef::VT_COUNT, count, 1);
  }
  void add_count_point_id(::flatbuffers::Offset<::flatbuffers::String> count_point_id) {
    fbb_.AddOffset(SunspecPointDef::VT_COUNT_POINT_ID, count_point_id);
  }
  void add_size(uint16_t size) {
    fbb_.AddElement<uint16_t>(SunspecPointDef::VT_SIZE, size, 0);
  }
  void add_sf(int16_t sf) {
    fbb_.AddElement<int16_t>(SunspecPointDef::VT_SF, sf, 0);
  }
  void add_sf_id(::flatbuffers::Offset<::flatbuffers::String> sf_id) {
    fbb_.AddOffset(SunspecPointDef::VT_SF_ID, sf_id);
  }
  void add_units(::flatbuffers::Offset<::flatbuffers::String> units) {
    fbb_.AddOffset(SunspecPointDef::VT_UNITS, units);
  }
  void add_access(SunspecPointAccessType access) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_ACCESS, static_cast<uint8_t>(access), 0);
  }
  void add_mandatory(SunspecPointMandatoryType mandatory) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_MANDATORY, static_cast<uint8_t>(mandatory), 1);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(SunspecPointDef::VT_LABEL, label);
  }
  explicit SunspecPointDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecPointDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecPointDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecPointDef> CreateSunspecPointDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    SunspecPointDataType type = SunspecPointDataType_kUndefinedType,
    uint16_t count = 1,
    ::flatbuffers::Offset<::flatbuffers::String> count_point_id = 0,
    uint16_t size = 0,
    int16_t sf = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sf_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> units = 0,
    SunspecPointAccessType access = SunspecPointAccessType_kR,
    SunspecPointMandatoryType mandatory = SunspecPointMandatoryType_kO,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0) {
  SunspecPointDefBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_units(units);
  builder_.add_sf_id(sf_id);
  builder_.add_count_point_id(count_point_id);
  builder_.add_id(id);
  builder_.add_sf(sf);
  builder_.add_size(size);
  builder_.add_count(count);
  builder_.add_mandatory(mandatory);
  builder_.add_access(access);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SunspecPointDef> CreateSunspecPointDefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    SunspecPointDataType type = SunspecPointDataType_kUndefinedType,
    uint16_t count = 1,
    const char *count_point_id = nullptr,
    uint16_t size = 0,
    int16_t sf = 0,
    const char *sf_id = nullptr,
    const char *units = nullptr,
    SunspecPointAccessType access = SunspecPointAccessType_kR,
    SunspecPointMandatoryType mandatory = SunspecPointMandatoryType_kO,
    const char *label = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto count_point_id__ = count_point_id ? _fbb.CreateString(count_point_id) : 0;
  auto sf_id__ = sf_id ? _fbb.CreateString(sf_id) : 0;
  auto units__ = units ? _fbb.CreateString(units) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return CreateSunspecPointDef(
      _fbb,
      id__,
      type,
      count,
      count_point_id__,
      size,
      sf,
      sf_id__,
      units__,
      access,
      mandatory,
      label__);
}

struct SunspecGroupPointDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecGroupPointDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_COUNT = 8,
    VT_COUNT_POINT_ID = 10,
    VT_POINTS = 12,
    VT_GROUPS = 14,
    VT_LABEL = 16
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  SunspecGroupType type() const {
    return static_cast<SunspecGroupType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  uint16_t count() const {
    return GetField<uint16_t>(VT_COUNT, 1);
  }
  const ::flatbuffers::String *count_point_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNT_POINT_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>> *points() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>> *>(VT_POINTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupPointDef>> *groups() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupPointDef>> *>(VT_GROUPS);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint16_t>(verifier, VT_COUNT, 2) &&
           VerifyOffset(verifier, VT_COUNT_POINT_ID) &&
           verifier.VerifyString(count_point_id()) &&
           VerifyOffset(verifier, VT_POINTS) &&
           verifier.VerifyVector(points()) &&
           verifier.VerifyVectorOfTables(points()) &&
           VerifyOffset(verifier, VT_GROUPS) &&
           verifier.VerifyVector(groups()) &&
           verifier.VerifyVectorOfTables(groups()) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           verifier.EndTable();
  }
};

struct SunspecGroupPointDefBuilder {
  typedef SunspecGroupPointDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(SunspecGroupPointDef::VT_ID, id);
  }
  void add_type(SunspecGroupType type) {
    fbb_.AddElement<uint8_t>(SunspecGroupPointDef::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_count(uint16_t count) {
    fbb_.AddElement<uint16_t>(SunspecGroupPointDef::VT_COUNT, count, 1);
  }
  void add_count_point_id(::flatbuffers::Offset<::flatbuffers::String> count_point_id) {
    fbb_.AddOffset(SunspecGroupPointDef::VT_COUNT_POINT_ID, count_point_id);
  }
  void add_points(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>>> points) {
    fbb_.AddOffset(SunspecGroupPointDef::VT_POINTS, points);
  }
  void add_groups(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupPointDef>>> groups) {
    fbb_.AddOffset(SunspecGroupPointDef::VT_GROUPS, groups);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(SunspecGroupPointDef::VT_LABEL, label);
  }
  explicit SunspecGroupPointDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecGroupPointDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecGroupPointDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecGroupPointDef> CreateSunspecGroupPointDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    SunspecGroupType type = SunspecGroupType_kGroup,
    uint16_t count = 1,
    ::flatbuffers::Offset<::flatbuffers::String> count_point_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>>> points = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupPointDef>>> groups = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0) {
  SunspecGroupPointDefBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_groups(groups);
  builder_.add_points(points);
  builder_.add_count_point_id(count_point_id);
  builder_.add_id(id);
  builder_.add_count(count);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SunspecGroupPointDef> CreateSunspecGroupPointDefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    SunspecGroupType type = SunspecGroupType_kGroup,
    uint16_t count = 1,
    const char *count_point_id = nullptr,
    const std::vector<::flatbuffers::Offset<SunspecPointDef>> *points = nullptr,
    const std::vector<::flatbuffers::Offset<SunspecGroupPointDef>> *groups = nullptr,
    const char *label = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto count_point_id__ = count_point_id ? _fbb.CreateString(count_point_id) : 0;
  auto points__ = points ? _fbb.CreateVector<::flatbuffers::Offset<SunspecPointDef>>(*points) : 0;
  auto groups__ = groups ? _fbb.CreateVector<::flatbuffers::Offset<SunspecGroupPointDef>>(*groups) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return CreateSunspecGroupPointDef(
      _fbb,
      id__,
      type,
      count,
      count_point_id__,
      points__,
      groups__,
      label__);
}

struct SunspecModelDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecModelDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_GROUP = 6
  };
  SunspecModelList id() const {
    return static_cast<SunspecModelList>(GetField<uint16_t>(VT_ID, 0));
  }
  const SunspecGroupPointDef *group() const {
    return GetPointer<const SunspecGroupPointDef *>(VT_GROUP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ID, 2) &&
           VerifyOffset(verifier, VT_GROUP) &&
           verifier.VerifyTable(group()) &&
           verifier.EndTable();
  }
};

struct SunspecModelDefBuilder {
  typedef SunspecModelDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(SunspecModelList id) {
    fbb_.AddElement<uint16_t>(SunspecModelDef::VT_ID, static_cast<uint16_t>(id), 0);
  }
  void add_group(::flatbuffers::Offset<SunspecGroupPointDef> group) {
    fbb_.AddOffset(SunspecModelDef::VT_GROUP, group);
  }
  explicit SunspecModelDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecModelDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecModelDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecModelDef> CreateSunspecModelDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SunspecModelList id = SunspecModelList_KModelInvalid,
    ::flatbuffers::Offset<SunspecGroupPointDef> group = 0) {
  SunspecModelDefBuilder builder_(_fbb);
  builder_.add_group(group);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const SunspecModelDef *GetSunspecModelDef(const void *buf) {
  return ::flatbuffers::GetRoot<SunspecModelDef>(buf);
}

inline const SunspecModelDef *GetSizePrefixedSunspecModelDef(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SunspecModelDef>(buf);
}

inline bool VerifySunspecModelDefBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SunspecModelDef>(nullptr);
}

inline bool VerifySizePrefixedSunspecModelDefBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SunspecModelDef>(nullptr);
}

inline void FinishSunspecModelDefBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SunspecModelDef> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSunspecModelDefBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SunspecModelDef> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_
