// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_
#define FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct Sint16;

struct Sint32;

struct Sint64;

struct Raw16;

struct Uint16;

struct Uint32;

struct Uint64;

struct Acc16;

struct Acc32;

struct Acc64;

struct Bitfield16;

struct Bitfield32;

struct Bitfield64;

struct Enum16;

struct Enum32;

struct Float32;

struct Float64;

struct Stringx;
struct StringxBuilder;

struct SunsSf;

struct Pad16;

struct IpAddr;

struct Ipv6Addr;

struct Eui48;

struct SunspecPointDef;
struct SunspecPointDefBuilder;

struct SunspecGroupDef;
struct SunspecGroupDefBuilder;

struct SunspecModelDef;
struct SunspecModelDefBuilder;

enum SunspecPointAccess : uint8_t {
  SunspecPointAccess_kR = 0,
  SunspecPointAccess_kRW = 1,
  SunspecPointAccess_MIN = SunspecPointAccess_kR,
  SunspecPointAccess_MAX = SunspecPointAccess_kRW
};

inline const SunspecPointAccess (&EnumValuesSunspecPointAccess())[2] {
  static const SunspecPointAccess values[] = {
    SunspecPointAccess_kR,
    SunspecPointAccess_kRW
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointAccess() {
  static const char * const names[3] = {
    "kR",
    "kRW",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointAccess(SunspecPointAccess e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointAccess_kR, SunspecPointAccess_kRW)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointAccess()[index];
}

enum SunspecPointMandatory : uint8_t {
  SunspecPointMandatory_kM = 0,
  SunspecPointMandatory_kO = 1,
  SunspecPointMandatory_MIN = SunspecPointMandatory_kM,
  SunspecPointMandatory_MAX = SunspecPointMandatory_kO
};

inline const SunspecPointMandatory (&EnumValuesSunspecPointMandatory())[2] {
  static const SunspecPointMandatory values[] = {
    SunspecPointMandatory_kM,
    SunspecPointMandatory_kO
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointMandatory() {
  static const char * const names[3] = {
    "kM",
    "kO",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointMandatory(SunspecPointMandatory e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointMandatory_kM, SunspecPointMandatory_kO)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointMandatory()[index];
}

enum SunspecPointData : uint8_t {
  SunspecPointData_NONE = 0,
  SunspecPointData_Sint16 = 1,
  SunspecPointData_Sint32 = 2,
  SunspecPointData_Sint64 = 3,
  SunspecPointData_Raw16 = 4,
  SunspecPointData_Uint16 = 5,
  SunspecPointData_Uint32 = 6,
  SunspecPointData_Uint64 = 7,
  SunspecPointData_Acc16 = 8,
  SunspecPointData_Acc32 = 9,
  SunspecPointData_Acc64 = 10,
  SunspecPointData_Bitfield16 = 11,
  SunspecPointData_Bitfield32 = 12,
  SunspecPointData_Bitfield64 = 13,
  SunspecPointData_Enum16 = 14,
  SunspecPointData_Enum32 = 15,
  SunspecPointData_Float32 = 16,
  SunspecPointData_Float64 = 17,
  SunspecPointData_Stringx = 18,
  SunspecPointData_SunsSf = 19,
  SunspecPointData_Pad16 = 20,
  SunspecPointData_IpAddr = 21,
  SunspecPointData_Ipv6Addr = 22,
  SunspecPointData_Eui48 = 23,
  SunspecPointData_MIN = SunspecPointData_NONE,
  SunspecPointData_MAX = SunspecPointData_Eui48
};

inline const SunspecPointData (&EnumValuesSunspecPointData())[24] {
  static const SunspecPointData values[] = {
    SunspecPointData_NONE,
    SunspecPointData_Sint16,
    SunspecPointData_Sint32,
    SunspecPointData_Sint64,
    SunspecPointData_Raw16,
    SunspecPointData_Uint16,
    SunspecPointData_Uint32,
    SunspecPointData_Uint64,
    SunspecPointData_Acc16,
    SunspecPointData_Acc32,
    SunspecPointData_Acc64,
    SunspecPointData_Bitfield16,
    SunspecPointData_Bitfield32,
    SunspecPointData_Bitfield64,
    SunspecPointData_Enum16,
    SunspecPointData_Enum32,
    SunspecPointData_Float32,
    SunspecPointData_Float64,
    SunspecPointData_Stringx,
    SunspecPointData_SunsSf,
    SunspecPointData_Pad16,
    SunspecPointData_IpAddr,
    SunspecPointData_Ipv6Addr,
    SunspecPointData_Eui48
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointData() {
  static const char * const names[25] = {
    "NONE",
    "Sint16",
    "Sint32",
    "Sint64",
    "Raw16",
    "Uint16",
    "Uint32",
    "Uint64",
    "Acc16",
    "Acc32",
    "Acc64",
    "Bitfield16",
    "Bitfield32",
    "Bitfield64",
    "Enum16",
    "Enum32",
    "Float32",
    "Float64",
    "Stringx",
    "SunsSf",
    "Pad16",
    "IpAddr",
    "Ipv6Addr",
    "Eui48",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointData(SunspecPointData e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointData_NONE, SunspecPointData_Eui48)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointData()[index];
}

template<typename T> struct SunspecPointDataTraits {
  static const SunspecPointData enum_value = SunspecPointData_NONE;
};

template<> struct SunspecPointDataTraits<Sint16> {
  static const SunspecPointData enum_value = SunspecPointData_Sint16;
};

template<> struct SunspecPointDataTraits<Sint32> {
  static const SunspecPointData enum_value = SunspecPointData_Sint32;
};

template<> struct SunspecPointDataTraits<Sint64> {
  static const SunspecPointData enum_value = SunspecPointData_Sint64;
};

template<> struct SunspecPointDataTraits<Raw16> {
  static const SunspecPointData enum_value = SunspecPointData_Raw16;
};

template<> struct SunspecPointDataTraits<Uint16> {
  static const SunspecPointData enum_value = SunspecPointData_Uint16;
};

template<> struct SunspecPointDataTraits<Uint32> {
  static const SunspecPointData enum_value = SunspecPointData_Uint32;
};

template<> struct SunspecPointDataTraits<Uint64> {
  static const SunspecPointData enum_value = SunspecPointData_Uint64;
};

template<> struct SunspecPointDataTraits<Acc16> {
  static const SunspecPointData enum_value = SunspecPointData_Acc16;
};

template<> struct SunspecPointDataTraits<Acc32> {
  static const SunspecPointData enum_value = SunspecPointData_Acc32;
};

template<> struct SunspecPointDataTraits<Acc64> {
  static const SunspecPointData enum_value = SunspecPointData_Acc64;
};

template<> struct SunspecPointDataTraits<Bitfield16> {
  static const SunspecPointData enum_value = SunspecPointData_Bitfield16;
};

template<> struct SunspecPointDataTraits<Bitfield32> {
  static const SunspecPointData enum_value = SunspecPointData_Bitfield32;
};

template<> struct SunspecPointDataTraits<Bitfield64> {
  static const SunspecPointData enum_value = SunspecPointData_Bitfield64;
};

template<> struct SunspecPointDataTraits<Enum16> {
  static const SunspecPointData enum_value = SunspecPointData_Enum16;
};

template<> struct SunspecPointDataTraits<Enum32> {
  static const SunspecPointData enum_value = SunspecPointData_Enum32;
};

template<> struct SunspecPointDataTraits<Float32> {
  static const SunspecPointData enum_value = SunspecPointData_Float32;
};

template<> struct SunspecPointDataTraits<Float64> {
  static const SunspecPointData enum_value = SunspecPointData_Float64;
};

template<> struct SunspecPointDataTraits<Stringx> {
  static const SunspecPointData enum_value = SunspecPointData_Stringx;
};

template<> struct SunspecPointDataTraits<SunsSf> {
  static const SunspecPointData enum_value = SunspecPointData_SunsSf;
};

template<> struct SunspecPointDataTraits<Pad16> {
  static const SunspecPointData enum_value = SunspecPointData_Pad16;
};

template<> struct SunspecPointDataTraits<IpAddr> {
  static const SunspecPointData enum_value = SunspecPointData_IpAddr;
};

template<> struct SunspecPointDataTraits<Ipv6Addr> {
  static const SunspecPointData enum_value = SunspecPointData_Ipv6Addr;
};

template<> struct SunspecPointDataTraits<Eui48> {
  static const SunspecPointData enum_value = SunspecPointData_Eui48;
};

bool VerifySunspecPointData(::flatbuffers::Verifier &verifier, const void *obj, SunspecPointData type);
bool VerifySunspecPointDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum SunspecGroupType : uint8_t {
  SunspecGroupType_kGroup = 0,
  SunspecGroupType_kSync = 1,
  SunspecGroupType_MIN = SunspecGroupType_kGroup,
  SunspecGroupType_MAX = SunspecGroupType_kSync
};

inline const SunspecGroupType (&EnumValuesSunspecGroupType())[2] {
  static const SunspecGroupType values[] = {
    SunspecGroupType_kGroup,
    SunspecGroupType_kSync
  };
  return values;
}

inline const char * const *EnumNamesSunspecGroupType() {
  static const char * const names[3] = {
    "kGroup",
    "kSync",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecGroupType(SunspecGroupType e) {
  if (::flatbuffers::IsOutRange(e, SunspecGroupType_kGroup, SunspecGroupType_kSync)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecGroupType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Sint16 FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t value_;

 public:
  Sint16()
      : value_(0) {
  }
  Sint16(int16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  int16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Sint16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Sint32 FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t value_;

 public:
  Sint32()
      : value_(0) {
  }
  Sint32(int32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  int32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Sint32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Sint64 FLATBUFFERS_FINAL_CLASS {
 private:
  int64_t value_;

 public:
  Sint64()
      : value_(0) {
  }
  Sint64(int64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  int64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Sint64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Raw16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  Raw16()
      : value_(0) {
  }
  Raw16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Raw16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Uint16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  Uint16()
      : value_(0) {
  }
  Uint16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Uint16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Uint32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  Uint32()
      : value_(0) {
  }
  Uint32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Uint32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Uint64 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t value_;

 public:
  Uint64()
      : value_(0) {
  }
  Uint64(uint64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Uint64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Acc16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  Acc16()
      : value_(0) {
  }
  Acc16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Acc16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Acc32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  Acc32()
      : value_(0) {
  }
  Acc32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Acc32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Acc64 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t value_;

 public:
  Acc64()
      : value_(0) {
  }
  Acc64(uint64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Acc64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Bitfield16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  Bitfield16()
      : value_(0) {
  }
  Bitfield16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Bitfield16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Bitfield32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  Bitfield32()
      : value_(0) {
  }
  Bitfield32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Bitfield32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Bitfield64 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t value_;

 public:
  Bitfield64()
      : value_(0) {
  }
  Bitfield64(uint64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Bitfield64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Enum16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  Enum16()
      : value_(0) {
  }
  Enum16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Enum16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Enum32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  Enum32()
      : value_(0) {
  }
  Enum32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Enum32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Float32 FLATBUFFERS_FINAL_CLASS {
 private:
  float value_;

 public:
  Float32()
      : value_(0) {
  }
  Float32(float _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  float value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Float32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Float64 FLATBUFFERS_FINAL_CLASS {
 private:
  double value_;

 public:
  Float64()
      : value_(0) {
  }
  Float64(double _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  double value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Float64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) SunsSf FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  SunsSf()
      : value_(0) {
  }
  SunsSf(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(SunsSf, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Pad16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  Pad16()
      : value_(0) {
  }
  Pad16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(Pad16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) IpAddr FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t octet1_;
  uint8_t octet2_;
  uint8_t octet3_;
  uint8_t octet4_;

 public:
  IpAddr()
      : octet1_(0),
        octet2_(0),
        octet3_(0),
        octet4_(0) {
  }
  IpAddr(uint8_t _octet1, uint8_t _octet2, uint8_t _octet3, uint8_t _octet4)
      : octet1_(::flatbuffers::EndianScalar(_octet1)),
        octet2_(::flatbuffers::EndianScalar(_octet2)),
        octet3_(::flatbuffers::EndianScalar(_octet3)),
        octet4_(::flatbuffers::EndianScalar(_octet4)) {
  }
  uint8_t octet1() const {
    return ::flatbuffers::EndianScalar(octet1_);
  }
  uint8_t octet2() const {
    return ::flatbuffers::EndianScalar(octet2_);
  }
  uint8_t octet3() const {
    return ::flatbuffers::EndianScalar(octet3_);
  }
  uint8_t octet4() const {
    return ::flatbuffers::EndianScalar(octet4_);
  }
};
FLATBUFFERS_STRUCT_END(IpAddr, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Ipv6Addr FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t value_[24];

 public:
  Ipv6Addr()
      : value_() {
  }
  Ipv6Addr(::flatbuffers::span<const uint8_t, 24> _value) {
    ::flatbuffers::CastToArray(value_).CopyFromSpan(_value);
  }
  const ::flatbuffers::Array<uint8_t, 24> *value() const {
    return &::flatbuffers::CastToArray(value_);
  }
};
FLATBUFFERS_STRUCT_END(Ipv6Addr, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Eui48 FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t value_[6];

 public:
  Eui48()
      : value_() {
  }
  Eui48(::flatbuffers::span<const uint8_t, 6> _value) {
    ::flatbuffers::CastToArray(value_).CopyFromSpan(_value);
  }
  const ::flatbuffers::Array<uint8_t, 6> *value() const {
    return &::flatbuffers::CastToArray(value_);
  }
};
FLATBUFFERS_STRUCT_END(Eui48, 6);

struct Stringx FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct StringxBuilder {
  typedef Stringx Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(Stringx::VT_VALUE, value);
  }
  explicit StringxBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Stringx> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Stringx>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Stringx> CreateStringx(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  StringxBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Stringx> CreateStringxDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return CreateStringx(
      _fbb,
      value__);
}

struct SunspecPointDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecPointDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DATA_TYPE = 6,
    VT_DATA = 8,
    VT_COUNT = 10,
    VT_COUNT_POINT_ID = 12,
    VT_SIZE = 14,
    VT_SF = 16,
    VT_SF_ID = 18,
    VT_UNITS = 20,
    VT_ACCESS = 22,
    VT_MANDATORY = 24,
    VT_LABEL = 26
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  SunspecPointData data_type() const {
    return static_cast<SunspecPointData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const Sint16 *data_as_Sint16() const {
    return data_type() == SunspecPointData_Sint16 ? static_cast<const Sint16 *>(data()) : nullptr;
  }
  const Sint32 *data_as_Sint32() const {
    return data_type() == SunspecPointData_Sint32 ? static_cast<const Sint32 *>(data()) : nullptr;
  }
  const Sint64 *data_as_Sint64() const {
    return data_type() == SunspecPointData_Sint64 ? static_cast<const Sint64 *>(data()) : nullptr;
  }
  const Raw16 *data_as_Raw16() const {
    return data_type() == SunspecPointData_Raw16 ? static_cast<const Raw16 *>(data()) : nullptr;
  }
  const Uint16 *data_as_Uint16() const {
    return data_type() == SunspecPointData_Uint16 ? static_cast<const Uint16 *>(data()) : nullptr;
  }
  const Uint32 *data_as_Uint32() const {
    return data_type() == SunspecPointData_Uint32 ? static_cast<const Uint32 *>(data()) : nullptr;
  }
  const Uint64 *data_as_Uint64() const {
    return data_type() == SunspecPointData_Uint64 ? static_cast<const Uint64 *>(data()) : nullptr;
  }
  const Acc16 *data_as_Acc16() const {
    return data_type() == SunspecPointData_Acc16 ? static_cast<const Acc16 *>(data()) : nullptr;
  }
  const Acc32 *data_as_Acc32() const {
    return data_type() == SunspecPointData_Acc32 ? static_cast<const Acc32 *>(data()) : nullptr;
  }
  const Acc64 *data_as_Acc64() const {
    return data_type() == SunspecPointData_Acc64 ? static_cast<const Acc64 *>(data()) : nullptr;
  }
  const Bitfield16 *data_as_Bitfield16() const {
    return data_type() == SunspecPointData_Bitfield16 ? static_cast<const Bitfield16 *>(data()) : nullptr;
  }
  const Bitfield32 *data_as_Bitfield32() const {
    return data_type() == SunspecPointData_Bitfield32 ? static_cast<const Bitfield32 *>(data()) : nullptr;
  }
  const Bitfield64 *data_as_Bitfield64() const {
    return data_type() == SunspecPointData_Bitfield64 ? static_cast<const Bitfield64 *>(data()) : nullptr;
  }
  const Enum16 *data_as_Enum16() const {
    return data_type() == SunspecPointData_Enum16 ? static_cast<const Enum16 *>(data()) : nullptr;
  }
  const Enum32 *data_as_Enum32() const {
    return data_type() == SunspecPointData_Enum32 ? static_cast<const Enum32 *>(data()) : nullptr;
  }
  const Float32 *data_as_Float32() const {
    return data_type() == SunspecPointData_Float32 ? static_cast<const Float32 *>(data()) : nullptr;
  }
  const Float64 *data_as_Float64() const {
    return data_type() == SunspecPointData_Float64 ? static_cast<const Float64 *>(data()) : nullptr;
  }
  const Stringx *data_as_Stringx() const {
    return data_type() == SunspecPointData_Stringx ? static_cast<const Stringx *>(data()) : nullptr;
  }
  const SunsSf *data_as_SunsSf() const {
    return data_type() == SunspecPointData_SunsSf ? static_cast<const SunsSf *>(data()) : nullptr;
  }
  const Pad16 *data_as_Pad16() const {
    return data_type() == SunspecPointData_Pad16 ? static_cast<const Pad16 *>(data()) : nullptr;
  }
  const IpAddr *data_as_IpAddr() const {
    return data_type() == SunspecPointData_IpAddr ? static_cast<const IpAddr *>(data()) : nullptr;
  }
  const Ipv6Addr *data_as_Ipv6Addr() const {
    return data_type() == SunspecPointData_Ipv6Addr ? static_cast<const Ipv6Addr *>(data()) : nullptr;
  }
  const Eui48 *data_as_Eui48() const {
    return data_type() == SunspecPointData_Eui48 ? static_cast<const Eui48 *>(data()) : nullptr;
  }
  uint16_t count() const {
    return GetField<uint16_t>(VT_COUNT, 1);
  }
  const ::flatbuffers::String *count_point_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNT_POINT_ID);
  }
  uint16_t size() const {
    return GetField<uint16_t>(VT_SIZE, 0);
  }
  int16_t sf() const {
    return GetField<int16_t>(VT_SF, 0);
  }
  const ::flatbuffers::String *sf_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SF_ID);
  }
  const ::flatbuffers::String *units() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UNITS);
  }
  SunspecPointAccess access() const {
    return static_cast<SunspecPointAccess>(GetField<uint8_t>(VT_ACCESS, 0));
  }
  SunspecPointMandatory mandatory() const {
    return static_cast<SunspecPointMandatory>(GetField<uint8_t>(VT_MANDATORY, 1));
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifySunspecPointData(verifier, data(), data_type()) &&
           VerifyField<uint16_t>(verifier, VT_COUNT, 2) &&
           VerifyOffset(verifier, VT_COUNT_POINT_ID) &&
           verifier.VerifyString(count_point_id()) &&
           VerifyField<uint16_t>(verifier, VT_SIZE, 2) &&
           VerifyField<int16_t>(verifier, VT_SF, 2) &&
           VerifyOffset(verifier, VT_SF_ID) &&
           verifier.VerifyString(sf_id()) &&
           VerifyOffset(verifier, VT_UNITS) &&
           verifier.VerifyString(units()) &&
           VerifyField<uint8_t>(verifier, VT_ACCESS, 1) &&
           VerifyField<uint8_t>(verifier, VT_MANDATORY, 1) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           verifier.EndTable();
  }
};

template<> inline const Sint16 *SunspecPointDef::data_as<Sint16>() const {
  return data_as_Sint16();
}

template<> inline const Sint32 *SunspecPointDef::data_as<Sint32>() const {
  return data_as_Sint32();
}

template<> inline const Sint64 *SunspecPointDef::data_as<Sint64>() const {
  return data_as_Sint64();
}

template<> inline const Raw16 *SunspecPointDef::data_as<Raw16>() const {
  return data_as_Raw16();
}

template<> inline const Uint16 *SunspecPointDef::data_as<Uint16>() const {
  return data_as_Uint16();
}

template<> inline const Uint32 *SunspecPointDef::data_as<Uint32>() const {
  return data_as_Uint32();
}

template<> inline const Uint64 *SunspecPointDef::data_as<Uint64>() const {
  return data_as_Uint64();
}

template<> inline const Acc16 *SunspecPointDef::data_as<Acc16>() const {
  return data_as_Acc16();
}

template<> inline const Acc32 *SunspecPointDef::data_as<Acc32>() const {
  return data_as_Acc32();
}

template<> inline const Acc64 *SunspecPointDef::data_as<Acc64>() const {
  return data_as_Acc64();
}

template<> inline const Bitfield16 *SunspecPointDef::data_as<Bitfield16>() const {
  return data_as_Bitfield16();
}

template<> inline const Bitfield32 *SunspecPointDef::data_as<Bitfield32>() const {
  return data_as_Bitfield32();
}

template<> inline const Bitfield64 *SunspecPointDef::data_as<Bitfield64>() const {
  return data_as_Bitfield64();
}

template<> inline const Enum16 *SunspecPointDef::data_as<Enum16>() const {
  return data_as_Enum16();
}

template<> inline const Enum32 *SunspecPointDef::data_as<Enum32>() const {
  return data_as_Enum32();
}

template<> inline const Float32 *SunspecPointDef::data_as<Float32>() const {
  return data_as_Float32();
}

template<> inline const Float64 *SunspecPointDef::data_as<Float64>() const {
  return data_as_Float64();
}

template<> inline const Stringx *SunspecPointDef::data_as<Stringx>() const {
  return data_as_Stringx();
}

template<> inline const SunsSf *SunspecPointDef::data_as<SunsSf>() const {
  return data_as_SunsSf();
}

template<> inline const Pad16 *SunspecPointDef::data_as<Pad16>() const {
  return data_as_Pad16();
}

template<> inline const IpAddr *SunspecPointDef::data_as<IpAddr>() const {
  return data_as_IpAddr();
}

template<> inline const Ipv6Addr *SunspecPointDef::data_as<Ipv6Addr>() const {
  return data_as_Ipv6Addr();
}

template<> inline const Eui48 *SunspecPointDef::data_as<Eui48>() const {
  return data_as_Eui48();
}

struct SunspecPointDefBuilder {
  typedef SunspecPointDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(SunspecPointDef::VT_ID, id);
  }
  void add_data_type(SunspecPointData data_type) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(SunspecPointDef::VT_DATA, data);
  }
  void add_count(uint16_t count) {
    fbb_.AddElement<uint16_t>(SunspecPointDef::VT_COUNT, count, 1);
  }
  void add_count_point_id(::flatbuffers::Offset<::flatbuffers::String> count_point_id) {
    fbb_.AddOffset(SunspecPointDef::VT_COUNT_POINT_ID, count_point_id);
  }
  void add_size(uint16_t size) {
    fbb_.AddElement<uint16_t>(SunspecPointDef::VT_SIZE, size, 0);
  }
  void add_sf(int16_t sf) {
    fbb_.AddElement<int16_t>(SunspecPointDef::VT_SF, sf, 0);
  }
  void add_sf_id(::flatbuffers::Offset<::flatbuffers::String> sf_id) {
    fbb_.AddOffset(SunspecPointDef::VT_SF_ID, sf_id);
  }
  void add_units(::flatbuffers::Offset<::flatbuffers::String> units) {
    fbb_.AddOffset(SunspecPointDef::VT_UNITS, units);
  }
  void add_access(SunspecPointAccess access) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_ACCESS, static_cast<uint8_t>(access), 0);
  }
  void add_mandatory(SunspecPointMandatory mandatory) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_MANDATORY, static_cast<uint8_t>(mandatory), 1);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(SunspecPointDef::VT_LABEL, label);
  }
  explicit SunspecPointDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecPointDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecPointDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecPointDef> CreateSunspecPointDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    SunspecPointData data_type = SunspecPointData_NONE,
    ::flatbuffers::Offset<void> data = 0,
    uint16_t count = 1,
    ::flatbuffers::Offset<::flatbuffers::String> count_point_id = 0,
    uint16_t size = 0,
    int16_t sf = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sf_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> units = 0,
    SunspecPointAccess access = SunspecPointAccess_kR,
    SunspecPointMandatory mandatory = SunspecPointMandatory_kO,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0) {
  SunspecPointDefBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_units(units);
  builder_.add_sf_id(sf_id);
  builder_.add_count_point_id(count_point_id);
  builder_.add_data(data);
  builder_.add_id(id);
  builder_.add_sf(sf);
  builder_.add_size(size);
  builder_.add_count(count);
  builder_.add_mandatory(mandatory);
  builder_.add_access(access);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SunspecPointDef> CreateSunspecPointDefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    SunspecPointData data_type = SunspecPointData_NONE,
    ::flatbuffers::Offset<void> data = 0,
    uint16_t count = 1,
    const char *count_point_id = nullptr,
    uint16_t size = 0,
    int16_t sf = 0,
    const char *sf_id = nullptr,
    const char *units = nullptr,
    SunspecPointAccess access = SunspecPointAccess_kR,
    SunspecPointMandatory mandatory = SunspecPointMandatory_kO,
    const char *label = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto count_point_id__ = count_point_id ? _fbb.CreateString(count_point_id) : 0;
  auto sf_id__ = sf_id ? _fbb.CreateString(sf_id) : 0;
  auto units__ = units ? _fbb.CreateString(units) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return CreateSunspecPointDef(
      _fbb,
      id__,
      data_type,
      data,
      count,
      count_point_id__,
      size,
      sf,
      sf_id__,
      units__,
      access,
      mandatory,
      label__);
}

struct SunspecGroupDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecGroupDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_COUNT = 8,
    VT_COUNT_POINT_ID = 10,
    VT_POINTS = 12,
    VT_GROUPS = 14,
    VT_LABEL = 16
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  SunspecGroupType type() const {
    return static_cast<SunspecGroupType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  uint16_t count() const {
    return GetField<uint16_t>(VT_COUNT, 1);
  }
  const ::flatbuffers::String *count_point_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNT_POINT_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>> *points() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>> *>(VT_POINTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>> *groups() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>> *>(VT_GROUPS);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint16_t>(verifier, VT_COUNT, 2) &&
           VerifyOffset(verifier, VT_COUNT_POINT_ID) &&
           verifier.VerifyString(count_point_id()) &&
           VerifyOffset(verifier, VT_POINTS) &&
           verifier.VerifyVector(points()) &&
           verifier.VerifyVectorOfTables(points()) &&
           VerifyOffset(verifier, VT_GROUPS) &&
           verifier.VerifyVector(groups()) &&
           verifier.VerifyVectorOfTables(groups()) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           verifier.EndTable();
  }
};

struct SunspecGroupDefBuilder {
  typedef SunspecGroupDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(SunspecGroupDef::VT_ID, id);
  }
  void add_type(SunspecGroupType type) {
    fbb_.AddElement<uint8_t>(SunspecGroupDef::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_count(uint16_t count) {
    fbb_.AddElement<uint16_t>(SunspecGroupDef::VT_COUNT, count, 1);
  }
  void add_count_point_id(::flatbuffers::Offset<::flatbuffers::String> count_point_id) {
    fbb_.AddOffset(SunspecGroupDef::VT_COUNT_POINT_ID, count_point_id);
  }
  void add_points(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>>> points) {
    fbb_.AddOffset(SunspecGroupDef::VT_POINTS, points);
  }
  void add_groups(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>>> groups) {
    fbb_.AddOffset(SunspecGroupDef::VT_GROUPS, groups);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(SunspecGroupDef::VT_LABEL, label);
  }
  explicit SunspecGroupDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecGroupDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecGroupDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecGroupDef> CreateSunspecGroupDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    SunspecGroupType type = SunspecGroupType_kGroup,
    uint16_t count = 1,
    ::flatbuffers::Offset<::flatbuffers::String> count_point_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>>> points = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>>> groups = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0) {
  SunspecGroupDefBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_groups(groups);
  builder_.add_points(points);
  builder_.add_count_point_id(count_point_id);
  builder_.add_id(id);
  builder_.add_count(count);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SunspecGroupDef> CreateSunspecGroupDefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    SunspecGroupType type = SunspecGroupType_kGroup,
    uint16_t count = 1,
    const char *count_point_id = nullptr,
    const std::vector<::flatbuffers::Offset<SunspecPointDef>> *points = nullptr,
    const std::vector<::flatbuffers::Offset<SunspecGroupDef>> *groups = nullptr,
    const char *label = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto count_point_id__ = count_point_id ? _fbb.CreateString(count_point_id) : 0;
  auto points__ = points ? _fbb.CreateVector<::flatbuffers::Offset<SunspecPointDef>>(*points) : 0;
  auto groups__ = groups ? _fbb.CreateVector<::flatbuffers::Offset<SunspecGroupDef>>(*groups) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return CreateSunspecGroupDef(
      _fbb,
      id__,
      type,
      count,
      count_point_id__,
      points__,
      groups__,
      label__);
}

struct SunspecModelDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecModelDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_GROUP = 6
  };
  uint16_t id() const {
    return GetField<uint16_t>(VT_ID, 65535);
  }
  const SunspecGroupDef *group() const {
    return GetPointer<const SunspecGroupDef *>(VT_GROUP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ID, 2) &&
           VerifyOffset(verifier, VT_GROUP) &&
           verifier.VerifyTable(group()) &&
           verifier.EndTable();
  }
};

struct SunspecModelDefBuilder {
  typedef SunspecModelDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint16_t id) {
    fbb_.AddElement<uint16_t>(SunspecModelDef::VT_ID, id, 65535);
  }
  void add_group(::flatbuffers::Offset<SunspecGroupDef> group) {
    fbb_.AddOffset(SunspecModelDef::VT_GROUP, group);
  }
  explicit SunspecModelDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecModelDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecModelDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecModelDef> CreateSunspecModelDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t id = 65535,
    ::flatbuffers::Offset<SunspecGroupDef> group = 0) {
  SunspecModelDefBuilder builder_(_fbb);
  builder_.add_group(group);
  builder_.add_id(id);
  return builder_.Finish();
}

inline bool VerifySunspecPointData(::flatbuffers::Verifier &verifier, const void *obj, SunspecPointData type) {
  switch (type) {
    case SunspecPointData_NONE: {
      return true;
    }
    case SunspecPointData_Sint16: {
      return verifier.VerifyField<Sint16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_Sint32: {
      return verifier.VerifyField<Sint32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_Sint64: {
      return verifier.VerifyField<Sint64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_Raw16: {
      return verifier.VerifyField<Raw16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_Uint16: {
      return verifier.VerifyField<Uint16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_Uint32: {
      return verifier.VerifyField<Uint32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_Uint64: {
      return verifier.VerifyField<Uint64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_Acc16: {
      return verifier.VerifyField<Acc16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_Acc32: {
      return verifier.VerifyField<Acc32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_Acc64: {
      return verifier.VerifyField<Acc64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_Bitfield16: {
      return verifier.VerifyField<Bitfield16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_Bitfield32: {
      return verifier.VerifyField<Bitfield32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_Bitfield64: {
      return verifier.VerifyField<Bitfield64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_Enum16: {
      return verifier.VerifyField<Enum16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_Enum32: {
      return verifier.VerifyField<Enum32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_Float32: {
      return verifier.VerifyField<Float32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_Float64: {
      return verifier.VerifyField<Float64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_Stringx: {
      auto ptr = reinterpret_cast<const Stringx *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SunspecPointData_SunsSf: {
      return verifier.VerifyField<SunsSf>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_Pad16: {
      return verifier.VerifyField<Pad16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_IpAddr: {
      return verifier.VerifyField<IpAddr>(static_cast<const uint8_t *>(obj), 0, 1);
    }
    case SunspecPointData_Ipv6Addr: {
      return verifier.VerifyField<Ipv6Addr>(static_cast<const uint8_t *>(obj), 0, 1);
    }
    case SunspecPointData_Eui48: {
      return verifier.VerifyField<Eui48>(static_cast<const uint8_t *>(obj), 0, 1);
    }
    default: return true;
  }
}

inline bool VerifySunspecPointDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySunspecPointData(
        verifier,  values->Get(i), types->GetEnum<SunspecPointData>(i))) {
      return false;
    }
  }
  return true;
}

inline const SunspecModelDef *GetSunspecModelDef(const void *buf) {
  return ::flatbuffers::GetRoot<SunspecModelDef>(buf);
}

inline const SunspecModelDef *GetSizePrefixedSunspecModelDef(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SunspecModelDef>(buf);
}

inline bool VerifySunspecModelDefBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SunspecModelDef>(nullptr);
}

inline bool VerifySizePrefixedSunspecModelDefBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SunspecModelDef>(nullptr);
}

inline void FinishSunspecModelDefBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SunspecModelDef> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSunspecModelDefBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SunspecModelDef> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_
