enum SunspecPointAccess :uint8
{
    kR,  /**< Only access Read supported */
    kRW, /**< Read and Write access supported */
}

/**
 * @brief Enumeration of SunspecPoint mandatory types.
 */
enum SunspecPointMandatory: uint8
{
    kM, /**< Point must be implemented */
    kO, /**< Point can be omitted */
}

struct Sint16
{
    value : int16;
}
  
struct Sint32
{
    value : int32 ;
}
  
struct Sint64
{
    value : int64;
}
  
struct Raw16
{
    value : uint16;
}
  
struct Uint16
{
    value : uint16 ;

}
  
struct Uint32
{
    value : uint32;

}
  
struct Uint64
{
    value : uint64;

}
  
struct Acc16
{
    value : uint16;

}
  
struct Acc32
{
    value : uint32;

}
  
struct Acc64
{
    value : uint64;

}
  
struct Bitfield16
{
    value : uint16;

}
  
struct Bitfield32
{
    value : uint32;

}
  
struct Bitfield64
{
    value : uint64;

}
  
struct Enum16
{
    value : uint16;

}
  
struct Enum32
{
    value : uint32;

}
  
struct Float32
{
    value : float;

}
  
struct Float64
{
    value : double;

}
  
table Stringx
{
    value : string;

}
  
struct SunsSf
{
    value : uint16;

}
  
struct Pad16
{
    value : uint16;

}
  
struct IpAddr
{
    octet1 : uint8;
    octet2 : uint8;
    octet3 : uint8;
    octet4 : uint8;

}
  
struct Ipv6Addr
{
    value : [uint8:24];

}
  
struct Eui48
{
    value : [uint8:6];

}

union SunspecPointData
{
    // UndefinedType = 0, /**< Undefined type */
    Sint16,             /**< Signed 16-bit integer */
    Sint32,             /**< Signed 32-bit integer */
    Sint64,             /**< Signed 64-bit integer */
    Raw16,             /**< 16-bit raw value */
    Uint16,            /**< Unsigned 16-bit integer */
    Uint32,            /**< Unsigned 32-bit integer */
    Uint64,            /**< Unsigned 64-bit integer */
    Acc16,             /**< Unsigned 16-bit accumulator(deprecated, in favor of uint16) */
    Acc32,             /**< Unsigned 32-bit accumulator (deprecated in favor of uint32) */
    Acc64,             /**< Unsigned 64-bit accumulator (deprecated in favor of uint64) */
    Bitfield16,        /**< 16-bit bitfield */
    Bitfield32,        /**< 32-bit bitfield */
    Bitfield64,        /**< 64-bit bitfield */
    Enum16,            /**< 16-bit enumeration */
    Enum32,            /**< 32-bit enumeration */
    Float32,           /**< 32-bit floating-point */
    Float64,           /**< 64-bit floating-point */
    Stringx,            /**< String (UTF-8 encoded) */
    SunsSf,            /**< Scale factor – Signed power of 10 multiplier (+) or divider (-) */
    Pad16,               /**< 16-bit pad used for alignment */
    IpAddr,            /**< IP Address as an unsigned 32-bit. */
    Ipv6Addr,          /**< 16-byte IP V6 address */
    Eui48,             /**< 48-bit MAC address */
}
table SunspecPointDef{
    id : string;
    data: SunspecPointData;
    // This is need because it can be specified as a constant in the model definition or in another point.
    count:uint16= 1;
    count_point_id : string;
    size: uint16;
    // This is need because it can be specified as a constant in the model definition or in another point.
    sf : int16;
    sf_id : string;
    units : string;
    access:SunspecPointAccess = kR;
    mandatory:SunspecPointMandatory = kO;
    label : string;
}


enum SunspecGroupType:uint8
{
    kGroup,
    kSync,
}

table SunspecGroupDef{
    id: string;
    type:SunspecGroupType = kGroup;
    count:uint16= 1;
    count_point_id:string;
    points: [SunspecPointDef];
    groups: [SunspecGroupDef];
    label:string;
}

table SunspecModelDef{
    id: uint16 = 0xffff;
    group:SunspecGroupDef;
}
root_type SunspecModelDef;