// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_
#define FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct kSint16;

struct kSint32;

struct kSint64;

struct kRaw16;

struct kUint16;

struct kUint32;

struct kUint64;

struct kAcc16;

struct KAcc32;

struct kAcc64;

struct kBitfield16;

struct kBitfield32;

struct kBitfield64;

struct kEnum16;

struct kEnum32;

struct kFloat32;

struct kFloat64;

struct kStringx;
struct kStringxBuilder;

struct kSunsSf;

struct kPad16;

struct kIpAddr;

struct kIpv6Addr;

struct kEui48;

struct SunspecPointDef;
struct SunspecPointDefBuilder;

struct SunspecGroupDef;
struct SunspecGroupDefBuilder;

struct SunspecModelDef;
struct SunspecModelDefBuilder;

enum SunspecPointAccessType : uint8_t {
  SunspecPointAccessType_kR = 0,
  SunspecPointAccessType_kRW = 1,
  SunspecPointAccessType_MIN = SunspecPointAccessType_kR,
  SunspecPointAccessType_MAX = SunspecPointAccessType_kRW
};

inline const SunspecPointAccessType (&EnumValuesSunspecPointAccessType())[2] {
  static const SunspecPointAccessType values[] = {
    SunspecPointAccessType_kR,
    SunspecPointAccessType_kRW
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointAccessType() {
  static const char * const names[3] = {
    "kR",
    "kRW",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointAccessType(SunspecPointAccessType e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointAccessType_kR, SunspecPointAccessType_kRW)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointAccessType()[index];
}

enum SunspecPointMandatoryType : uint8_t {
  SunspecPointMandatoryType_kM = 0,
  SunspecPointMandatoryType_kO = 1,
  SunspecPointMandatoryType_MIN = SunspecPointMandatoryType_kM,
  SunspecPointMandatoryType_MAX = SunspecPointMandatoryType_kO
};

inline const SunspecPointMandatoryType (&EnumValuesSunspecPointMandatoryType())[2] {
  static const SunspecPointMandatoryType values[] = {
    SunspecPointMandatoryType_kM,
    SunspecPointMandatoryType_kO
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointMandatoryType() {
  static const char * const names[3] = {
    "kM",
    "kO",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointMandatoryType(SunspecPointMandatoryType e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointMandatoryType_kM, SunspecPointMandatoryType_kO)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointMandatoryType()[index];
}

enum SunspecPointData : uint8_t {
  SunspecPointData_NONE = 0,
  SunspecPointData_kSint16 = 1,
  SunspecPointData_kSint32 = 2,
  SunspecPointData_kSint64 = 3,
  SunspecPointData_kRaw16 = 4,
  SunspecPointData_kUint16 = 5,
  SunspecPointData_kUint32 = 6,
  SunspecPointData_kUint64 = 7,
  SunspecPointData_kAcc16 = 8,
  SunspecPointData_KAcc32 = 9,
  SunspecPointData_kAcc64 = 10,
  SunspecPointData_kBitfield16 = 11,
  SunspecPointData_kBitfield32 = 12,
  SunspecPointData_kBitfield64 = 13,
  SunspecPointData_kEnum16 = 14,
  SunspecPointData_kEnum32 = 15,
  SunspecPointData_kFloat32 = 16,
  SunspecPointData_kFloat64 = 17,
  SunspecPointData_kStringx = 18,
  SunspecPointData_kSunsSf = 19,
  SunspecPointData_kPad16 = 20,
  SunspecPointData_kIpAddr = 21,
  SunspecPointData_kIpv6Addr = 22,
  SunspecPointData_kEui48 = 23,
  SunspecPointData_MIN = SunspecPointData_NONE,
  SunspecPointData_MAX = SunspecPointData_kEui48
};

inline const SunspecPointData (&EnumValuesSunspecPointData())[24] {
  static const SunspecPointData values[] = {
    SunspecPointData_NONE,
    SunspecPointData_kSint16,
    SunspecPointData_kSint32,
    SunspecPointData_kSint64,
    SunspecPointData_kRaw16,
    SunspecPointData_kUint16,
    SunspecPointData_kUint32,
    SunspecPointData_kUint64,
    SunspecPointData_kAcc16,
    SunspecPointData_KAcc32,
    SunspecPointData_kAcc64,
    SunspecPointData_kBitfield16,
    SunspecPointData_kBitfield32,
    SunspecPointData_kBitfield64,
    SunspecPointData_kEnum16,
    SunspecPointData_kEnum32,
    SunspecPointData_kFloat32,
    SunspecPointData_kFloat64,
    SunspecPointData_kStringx,
    SunspecPointData_kSunsSf,
    SunspecPointData_kPad16,
    SunspecPointData_kIpAddr,
    SunspecPointData_kIpv6Addr,
    SunspecPointData_kEui48
  };
  return values;
}

inline const char * const *EnumNamesSunspecPointData() {
  static const char * const names[25] = {
    "NONE",
    "kSint16",
    "kSint32",
    "kSint64",
    "kRaw16",
    "kUint16",
    "kUint32",
    "kUint64",
    "kAcc16",
    "KAcc32",
    "kAcc64",
    "kBitfield16",
    "kBitfield32",
    "kBitfield64",
    "kEnum16",
    "kEnum32",
    "kFloat32",
    "kFloat64",
    "kStringx",
    "kSunsSf",
    "kPad16",
    "kIpAddr",
    "kIpv6Addr",
    "kEui48",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecPointData(SunspecPointData e) {
  if (::flatbuffers::IsOutRange(e, SunspecPointData_NONE, SunspecPointData_kEui48)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecPointData()[index];
}

template<typename T> struct SunspecPointDataTraits {
  static const SunspecPointData enum_value = SunspecPointData_NONE;
};

template<> struct SunspecPointDataTraits<kSint16> {
  static const SunspecPointData enum_value = SunspecPointData_kSint16;
};

template<> struct SunspecPointDataTraits<kSint32> {
  static const SunspecPointData enum_value = SunspecPointData_kSint32;
};

template<> struct SunspecPointDataTraits<kSint64> {
  static const SunspecPointData enum_value = SunspecPointData_kSint64;
};

template<> struct SunspecPointDataTraits<kRaw16> {
  static const SunspecPointData enum_value = SunspecPointData_kRaw16;
};

template<> struct SunspecPointDataTraits<kUint16> {
  static const SunspecPointData enum_value = SunspecPointData_kUint16;
};

template<> struct SunspecPointDataTraits<kUint32> {
  static const SunspecPointData enum_value = SunspecPointData_kUint32;
};

template<> struct SunspecPointDataTraits<kUint64> {
  static const SunspecPointData enum_value = SunspecPointData_kUint64;
};

template<> struct SunspecPointDataTraits<kAcc16> {
  static const SunspecPointData enum_value = SunspecPointData_kAcc16;
};

template<> struct SunspecPointDataTraits<KAcc32> {
  static const SunspecPointData enum_value = SunspecPointData_KAcc32;
};

template<> struct SunspecPointDataTraits<kAcc64> {
  static const SunspecPointData enum_value = SunspecPointData_kAcc64;
};

template<> struct SunspecPointDataTraits<kBitfield16> {
  static const SunspecPointData enum_value = SunspecPointData_kBitfield16;
};

template<> struct SunspecPointDataTraits<kBitfield32> {
  static const SunspecPointData enum_value = SunspecPointData_kBitfield32;
};

template<> struct SunspecPointDataTraits<kBitfield64> {
  static const SunspecPointData enum_value = SunspecPointData_kBitfield64;
};

template<> struct SunspecPointDataTraits<kEnum16> {
  static const SunspecPointData enum_value = SunspecPointData_kEnum16;
};

template<> struct SunspecPointDataTraits<kEnum32> {
  static const SunspecPointData enum_value = SunspecPointData_kEnum32;
};

template<> struct SunspecPointDataTraits<kFloat32> {
  static const SunspecPointData enum_value = SunspecPointData_kFloat32;
};

template<> struct SunspecPointDataTraits<kFloat64> {
  static const SunspecPointData enum_value = SunspecPointData_kFloat64;
};

template<> struct SunspecPointDataTraits<kStringx> {
  static const SunspecPointData enum_value = SunspecPointData_kStringx;
};

template<> struct SunspecPointDataTraits<kSunsSf> {
  static const SunspecPointData enum_value = SunspecPointData_kSunsSf;
};

template<> struct SunspecPointDataTraits<kPad16> {
  static const SunspecPointData enum_value = SunspecPointData_kPad16;
};

template<> struct SunspecPointDataTraits<kIpAddr> {
  static const SunspecPointData enum_value = SunspecPointData_kIpAddr;
};

template<> struct SunspecPointDataTraits<kIpv6Addr> {
  static const SunspecPointData enum_value = SunspecPointData_kIpv6Addr;
};

template<> struct SunspecPointDataTraits<kEui48> {
  static const SunspecPointData enum_value = SunspecPointData_kEui48;
};

bool VerifySunspecPointData(::flatbuffers::Verifier &verifier, const void *obj, SunspecPointData type);
bool VerifySunspecPointDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum SunspecGroupType : uint8_t {
  SunspecGroupType_kGroup = 0,
  SunspecGroupType_kSync = 1,
  SunspecGroupType_MIN = SunspecGroupType_kGroup,
  SunspecGroupType_MAX = SunspecGroupType_kSync
};

inline const SunspecGroupType (&EnumValuesSunspecGroupType())[2] {
  static const SunspecGroupType values[] = {
    SunspecGroupType_kGroup,
    SunspecGroupType_kSync
  };
  return values;
}

inline const char * const *EnumNamesSunspecGroupType() {
  static const char * const names[3] = {
    "kGroup",
    "kSync",
    nullptr
  };
  return names;
}

inline const char *EnumNameSunspecGroupType(SunspecGroupType e) {
  if (::flatbuffers::IsOutRange(e, SunspecGroupType_kGroup, SunspecGroupType_kSync)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSunspecGroupType()[index];
}

enum SunspecModelList : uint16_t {
  SunspecModelList_KModelInvalid = 0,
  SunspecModelList_kModel1 = 1,
  SunspecModelList_kModel2 = 2,
  SunspecModelList_kModel3 = 3,
  SunspecModelList_kModel4 = 4,
  SunspecModelList_kModel5 = 5,
  SunspecModelList_kModel6 = 6,
  SunspecModelList_kModel7 = 7,
  SunspecModelList_kModel8 = 8,
  SunspecModelList_kModel9 = 9,
  SunspecModelList_kModel10 = 10,
  SunspecModelList_kModel11 = 11,
  SunspecModelList_kModel12 = 12,
  SunspecModelList_kModel13 = 13,
  SunspecModelList_kModel14 = 14,
  SunspecModelList_kModel15 = 15,
  SunspecModelList_kModel16 = 16,
  SunspecModelList_kModel17 = 17,
  SunspecModelList_kModel18 = 18,
  SunspecModelList_kModel19 = 19,
  SunspecModelList_kModel101 = 101,
  SunspecModelList_kModel102 = 102,
  SunspecModelList_kModel103 = 103,
  SunspecModelList_kModel111 = 111,
  SunspecModelList_kModel112 = 112,
  SunspecModelList_kModel113 = 113,
  SunspecModelList_kModel120 = 120,
  SunspecModelList_kModel121 = 121,
  SunspecModelList_kModel122 = 122,
  SunspecModelList_kModel123 = 123,
  SunspecModelList_kModel124 = 124,
  SunspecModelList_kModel125 = 125,
  SunspecModelList_kModel126 = 126,
  SunspecModelList_kModel127 = 127,
  SunspecModelList_kModel128 = 128,
  SunspecModelList_kModel129 = 129,
  SunspecModelList_kModel130 = 130,
  SunspecModelList_kModel131 = 131,
  SunspecModelList_kModel132 = 132,
  SunspecModelList_kModel133 = 133,
  SunspecModelList_kModel134 = 134,
  SunspecModelList_kModel135 = 135,
  SunspecModelList_kModel136 = 136,
  SunspecModelList_kModel137 = 137,
  SunspecModelList_kModel138 = 138,
  SunspecModelList_kModel139 = 139,
  SunspecModelList_kModel140 = 140,
  SunspecModelList_kModel141 = 141,
  SunspecModelList_kModel142 = 142,
  SunspecModelList_kModel143 = 143,
  SunspecModelList_kModel144 = 144,
  SunspecModelList_kModel145 = 145,
  SunspecModelList_kModel160 = 160,
  SunspecModelList_kModel201 = 201,
  SunspecModelList_kModel202 = 202,
  SunspecModelList_kModel203 = 203,
  SunspecModelList_kModel204 = 204,
  SunspecModelList_kModel211 = 211,
  SunspecModelList_kModel212 = 212,
  SunspecModelList_kModel213 = 213,
  SunspecModelList_kModel214 = 214,
  SunspecModelList_kModel220 = 220,
  SunspecModelList_kModel302 = 302,
  SunspecModelList_kModel303 = 303,
  SunspecModelList_kModel304 = 304,
  SunspecModelList_kModel305 = 305,
  SunspecModelList_kModel306 = 306,
  SunspecModelList_kModel307 = 307,
  SunspecModelList_kModel308 = 308,
  SunspecModelList_kModel401 = 401,
  SunspecModelList_kModel402 = 402,
  SunspecModelList_kModel403 = 403,
  SunspecModelList_kModel404 = 404,
  SunspecModelList_kModel501 = 501,
  SunspecModelList_kModel502 = 502,
  SunspecModelList_kModel601 = 601,
  SunspecModelList_kModel701 = 701,
  SunspecModelList_kModel702 = 702,
  SunspecModelList_kModel703 = 703,
  SunspecModelList_kModel704 = 704,
  SunspecModelList_kModel705 = 705,
  SunspecModelList_kModel706 = 706,
  SunspecModelList_kModel707 = 707,
  SunspecModelList_kModel708 = 708,
  SunspecModelList_kModel709 = 709,
  SunspecModelList_kModel710 = 710,
  SunspecModelList_kModel711 = 711,
  SunspecModelList_kModel712 = 712,
  SunspecModelList_kModel713 = 713,
  SunspecModelList_kModel714 = 714,
  SunspecModelList_kModel715 = 715,
  SunspecModelList_kModel801 = 801,
  SunspecModelList_kModel802 = 802,
  SunspecModelList_kModel803 = 803,
  SunspecModelList_kModel804 = 804,
  SunspecModelList_kModel805 = 805,
  SunspecModelList_kModel806 = 806,
  SunspecModelList_kModel807 = 807,
  SunspecModelList_kModel808 = 808,
  SunspecModelList_kModel809 = 809,
  SunspecModelList_kModel63001 = 63001,
  SunspecModelList_kModel64001 = 64001,
  SunspecModelList_kModel64020 = 64020,
  SunspecModelList_kModel64101 = 64101,
  SunspecModelList_kModel64111 = 64111,
  SunspecModelList_kModel64112 = 64112,
  SunspecModelList_kModel64410 = 64410,
  SunspecModelList_kModel64411 = 64411,
  SunspecModelList_kModel64412 = 64412,
  SunspecModelList_kModel64413 = 64413,
  SunspecModelList_kModel64414 = 64414,
  SunspecModelList_kModel64415 = 64415,
  SunspecModelList_kModelEnd = 65535,
  SunspecModelList_MIN = SunspecModelList_KModelInvalid,
  SunspecModelList_MAX = SunspecModelList_kModelEnd
};

inline const SunspecModelList (&EnumValuesSunspecModelList())[113] {
  static const SunspecModelList values[] = {
    SunspecModelList_KModelInvalid,
    SunspecModelList_kModel1,
    SunspecModelList_kModel2,
    SunspecModelList_kModel3,
    SunspecModelList_kModel4,
    SunspecModelList_kModel5,
    SunspecModelList_kModel6,
    SunspecModelList_kModel7,
    SunspecModelList_kModel8,
    SunspecModelList_kModel9,
    SunspecModelList_kModel10,
    SunspecModelList_kModel11,
    SunspecModelList_kModel12,
    SunspecModelList_kModel13,
    SunspecModelList_kModel14,
    SunspecModelList_kModel15,
    SunspecModelList_kModel16,
    SunspecModelList_kModel17,
    SunspecModelList_kModel18,
    SunspecModelList_kModel19,
    SunspecModelList_kModel101,
    SunspecModelList_kModel102,
    SunspecModelList_kModel103,
    SunspecModelList_kModel111,
    SunspecModelList_kModel112,
    SunspecModelList_kModel113,
    SunspecModelList_kModel120,
    SunspecModelList_kModel121,
    SunspecModelList_kModel122,
    SunspecModelList_kModel123,
    SunspecModelList_kModel124,
    SunspecModelList_kModel125,
    SunspecModelList_kModel126,
    SunspecModelList_kModel127,
    SunspecModelList_kModel128,
    SunspecModelList_kModel129,
    SunspecModelList_kModel130,
    SunspecModelList_kModel131,
    SunspecModelList_kModel132,
    SunspecModelList_kModel133,
    SunspecModelList_kModel134,
    SunspecModelList_kModel135,
    SunspecModelList_kModel136,
    SunspecModelList_kModel137,
    SunspecModelList_kModel138,
    SunspecModelList_kModel139,
    SunspecModelList_kModel140,
    SunspecModelList_kModel141,
    SunspecModelList_kModel142,
    SunspecModelList_kModel143,
    SunspecModelList_kModel144,
    SunspecModelList_kModel145,
    SunspecModelList_kModel160,
    SunspecModelList_kModel201,
    SunspecModelList_kModel202,
    SunspecModelList_kModel203,
    SunspecModelList_kModel204,
    SunspecModelList_kModel211,
    SunspecModelList_kModel212,
    SunspecModelList_kModel213,
    SunspecModelList_kModel214,
    SunspecModelList_kModel220,
    SunspecModelList_kModel302,
    SunspecModelList_kModel303,
    SunspecModelList_kModel304,
    SunspecModelList_kModel305,
    SunspecModelList_kModel306,
    SunspecModelList_kModel307,
    SunspecModelList_kModel308,
    SunspecModelList_kModel401,
    SunspecModelList_kModel402,
    SunspecModelList_kModel403,
    SunspecModelList_kModel404,
    SunspecModelList_kModel501,
    SunspecModelList_kModel502,
    SunspecModelList_kModel601,
    SunspecModelList_kModel701,
    SunspecModelList_kModel702,
    SunspecModelList_kModel703,
    SunspecModelList_kModel704,
    SunspecModelList_kModel705,
    SunspecModelList_kModel706,
    SunspecModelList_kModel707,
    SunspecModelList_kModel708,
    SunspecModelList_kModel709,
    SunspecModelList_kModel710,
    SunspecModelList_kModel711,
    SunspecModelList_kModel712,
    SunspecModelList_kModel713,
    SunspecModelList_kModel714,
    SunspecModelList_kModel715,
    SunspecModelList_kModel801,
    SunspecModelList_kModel802,
    SunspecModelList_kModel803,
    SunspecModelList_kModel804,
    SunspecModelList_kModel805,
    SunspecModelList_kModel806,
    SunspecModelList_kModel807,
    SunspecModelList_kModel808,
    SunspecModelList_kModel809,
    SunspecModelList_kModel63001,
    SunspecModelList_kModel64001,
    SunspecModelList_kModel64020,
    SunspecModelList_kModel64101,
    SunspecModelList_kModel64111,
    SunspecModelList_kModel64112,
    SunspecModelList_kModel64410,
    SunspecModelList_kModel64411,
    SunspecModelList_kModel64412,
    SunspecModelList_kModel64413,
    SunspecModelList_kModel64414,
    SunspecModelList_kModel64415,
    SunspecModelList_kModelEnd
  };
  return values;
}

inline const char *EnumNameSunspecModelList(SunspecModelList e) {
  switch (e) {
    case SunspecModelList_KModelInvalid: return "KModelInvalid";
    case SunspecModelList_kModel1: return "kModel1";
    case SunspecModelList_kModel2: return "kModel2";
    case SunspecModelList_kModel3: return "kModel3";
    case SunspecModelList_kModel4: return "kModel4";
    case SunspecModelList_kModel5: return "kModel5";
    case SunspecModelList_kModel6: return "kModel6";
    case SunspecModelList_kModel7: return "kModel7";
    case SunspecModelList_kModel8: return "kModel8";
    case SunspecModelList_kModel9: return "kModel9";
    case SunspecModelList_kModel10: return "kModel10";
    case SunspecModelList_kModel11: return "kModel11";
    case SunspecModelList_kModel12: return "kModel12";
    case SunspecModelList_kModel13: return "kModel13";
    case SunspecModelList_kModel14: return "kModel14";
    case SunspecModelList_kModel15: return "kModel15";
    case SunspecModelList_kModel16: return "kModel16";
    case SunspecModelList_kModel17: return "kModel17";
    case SunspecModelList_kModel18: return "kModel18";
    case SunspecModelList_kModel19: return "kModel19";
    case SunspecModelList_kModel101: return "kModel101";
    case SunspecModelList_kModel102: return "kModel102";
    case SunspecModelList_kModel103: return "kModel103";
    case SunspecModelList_kModel111: return "kModel111";
    case SunspecModelList_kModel112: return "kModel112";
    case SunspecModelList_kModel113: return "kModel113";
    case SunspecModelList_kModel120: return "kModel120";
    case SunspecModelList_kModel121: return "kModel121";
    case SunspecModelList_kModel122: return "kModel122";
    case SunspecModelList_kModel123: return "kModel123";
    case SunspecModelList_kModel124: return "kModel124";
    case SunspecModelList_kModel125: return "kModel125";
    case SunspecModelList_kModel126: return "kModel126";
    case SunspecModelList_kModel127: return "kModel127";
    case SunspecModelList_kModel128: return "kModel128";
    case SunspecModelList_kModel129: return "kModel129";
    case SunspecModelList_kModel130: return "kModel130";
    case SunspecModelList_kModel131: return "kModel131";
    case SunspecModelList_kModel132: return "kModel132";
    case SunspecModelList_kModel133: return "kModel133";
    case SunspecModelList_kModel134: return "kModel134";
    case SunspecModelList_kModel135: return "kModel135";
    case SunspecModelList_kModel136: return "kModel136";
    case SunspecModelList_kModel137: return "kModel137";
    case SunspecModelList_kModel138: return "kModel138";
    case SunspecModelList_kModel139: return "kModel139";
    case SunspecModelList_kModel140: return "kModel140";
    case SunspecModelList_kModel141: return "kModel141";
    case SunspecModelList_kModel142: return "kModel142";
    case SunspecModelList_kModel143: return "kModel143";
    case SunspecModelList_kModel144: return "kModel144";
    case SunspecModelList_kModel145: return "kModel145";
    case SunspecModelList_kModel160: return "kModel160";
    case SunspecModelList_kModel201: return "kModel201";
    case SunspecModelList_kModel202: return "kModel202";
    case SunspecModelList_kModel203: return "kModel203";
    case SunspecModelList_kModel204: return "kModel204";
    case SunspecModelList_kModel211: return "kModel211";
    case SunspecModelList_kModel212: return "kModel212";
    case SunspecModelList_kModel213: return "kModel213";
    case SunspecModelList_kModel214: return "kModel214";
    case SunspecModelList_kModel220: return "kModel220";
    case SunspecModelList_kModel302: return "kModel302";
    case SunspecModelList_kModel303: return "kModel303";
    case SunspecModelList_kModel304: return "kModel304";
    case SunspecModelList_kModel305: return "kModel305";
    case SunspecModelList_kModel306: return "kModel306";
    case SunspecModelList_kModel307: return "kModel307";
    case SunspecModelList_kModel308: return "kModel308";
    case SunspecModelList_kModel401: return "kModel401";
    case SunspecModelList_kModel402: return "kModel402";
    case SunspecModelList_kModel403: return "kModel403";
    case SunspecModelList_kModel404: return "kModel404";
    case SunspecModelList_kModel501: return "kModel501";
    case SunspecModelList_kModel502: return "kModel502";
    case SunspecModelList_kModel601: return "kModel601";
    case SunspecModelList_kModel701: return "kModel701";
    case SunspecModelList_kModel702: return "kModel702";
    case SunspecModelList_kModel703: return "kModel703";
    case SunspecModelList_kModel704: return "kModel704";
    case SunspecModelList_kModel705: return "kModel705";
    case SunspecModelList_kModel706: return "kModel706";
    case SunspecModelList_kModel707: return "kModel707";
    case SunspecModelList_kModel708: return "kModel708";
    case SunspecModelList_kModel709: return "kModel709";
    case SunspecModelList_kModel710: return "kModel710";
    case SunspecModelList_kModel711: return "kModel711";
    case SunspecModelList_kModel712: return "kModel712";
    case SunspecModelList_kModel713: return "kModel713";
    case SunspecModelList_kModel714: return "kModel714";
    case SunspecModelList_kModel715: return "kModel715";
    case SunspecModelList_kModel801: return "kModel801";
    case SunspecModelList_kModel802: return "kModel802";
    case SunspecModelList_kModel803: return "kModel803";
    case SunspecModelList_kModel804: return "kModel804";
    case SunspecModelList_kModel805: return "kModel805";
    case SunspecModelList_kModel806: return "kModel806";
    case SunspecModelList_kModel807: return "kModel807";
    case SunspecModelList_kModel808: return "kModel808";
    case SunspecModelList_kModel809: return "kModel809";
    case SunspecModelList_kModel63001: return "kModel63001";
    case SunspecModelList_kModel64001: return "kModel64001";
    case SunspecModelList_kModel64020: return "kModel64020";
    case SunspecModelList_kModel64101: return "kModel64101";
    case SunspecModelList_kModel64111: return "kModel64111";
    case SunspecModelList_kModel64112: return "kModel64112";
    case SunspecModelList_kModel64410: return "kModel64410";
    case SunspecModelList_kModel64411: return "kModel64411";
    case SunspecModelList_kModel64412: return "kModel64412";
    case SunspecModelList_kModel64413: return "kModel64413";
    case SunspecModelList_kModel64414: return "kModel64414";
    case SunspecModelList_kModel64415: return "kModel64415";
    case SunspecModelList_kModelEnd: return "kModelEnd";
    default: return "";
  }
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kSint16 FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t value_;

 public:
  kSint16()
      : value_(0) {
  }
  kSint16(int16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  int16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kSint16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) kSint32 FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t value_;

 public:
  kSint32()
      : value_(0) {
  }
  kSint32(int32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  int32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kSint32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) kSint64 FLATBUFFERS_FINAL_CLASS {
 private:
  int64_t value_;

 public:
  kSint64()
      : value_(0) {
  }
  kSint64(int64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  int64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kSint64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kRaw16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  kRaw16()
      : value_(0) {
  }
  kRaw16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kRaw16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kUint16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  kUint16()
      : value_(0) {
  }
  kUint16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kUint16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) kUint32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  kUint32()
      : value_(0) {
  }
  kUint32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kUint32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) kUint64 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t value_;

 public:
  kUint64()
      : value_(0) {
  }
  kUint64(uint64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kUint64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kAcc16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  kAcc16()
      : value_(0) {
  }
  kAcc16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kAcc16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) KAcc32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  KAcc32()
      : value_(0) {
  }
  KAcc32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(KAcc32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) kAcc64 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t value_;

 public:
  kAcc64()
      : value_(0) {
  }
  kAcc64(uint64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kAcc64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kBitfield16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  kBitfield16()
      : value_(0) {
  }
  kBitfield16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kBitfield16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) kBitfield32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  kBitfield32()
      : value_(0) {
  }
  kBitfield32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kBitfield32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) kBitfield64 FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t value_;

 public:
  kBitfield64()
      : value_(0) {
  }
  kBitfield64(uint64_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint64_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kBitfield64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kEnum16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  kEnum16()
      : value_(0) {
  }
  kEnum16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kEnum16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) kEnum32 FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t value_;

 public:
  kEnum32()
      : value_(0) {
  }
  kEnum32(uint32_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint32_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kEnum32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) kFloat32 FLATBUFFERS_FINAL_CLASS {
 private:
  float value_;

 public:
  kFloat32()
      : value_(0) {
  }
  kFloat32(float _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  float value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kFloat32, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) kFloat64 FLATBUFFERS_FINAL_CLASS {
 private:
  double value_;

 public:
  kFloat64()
      : value_(0) {
  }
  kFloat64(double _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  double value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kFloat64, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kSunsSf FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  kSunsSf()
      : value_(0) {
  }
  kSunsSf(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kSunsSf, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) kPad16 FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t value_;

 public:
  kPad16()
      : value_(0) {
  }
  kPad16(uint16_t _value)
      : value_(::flatbuffers::EndianScalar(_value)) {
  }
  uint16_t value() const {
    return ::flatbuffers::EndianScalar(value_);
  }
};
FLATBUFFERS_STRUCT_END(kPad16, 2);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) kIpAddr FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t octet1_;
  uint8_t octet2_;
  uint8_t octet3_;
  uint8_t octet4_;

 public:
  kIpAddr()
      : octet1_(0),
        octet2_(0),
        octet3_(0),
        octet4_(0) {
  }
  kIpAddr(uint8_t _octet1, uint8_t _octet2, uint8_t _octet3, uint8_t _octet4)
      : octet1_(::flatbuffers::EndianScalar(_octet1)),
        octet2_(::flatbuffers::EndianScalar(_octet2)),
        octet3_(::flatbuffers::EndianScalar(_octet3)),
        octet4_(::flatbuffers::EndianScalar(_octet4)) {
  }
  uint8_t octet1() const {
    return ::flatbuffers::EndianScalar(octet1_);
  }
  uint8_t octet2() const {
    return ::flatbuffers::EndianScalar(octet2_);
  }
  uint8_t octet3() const {
    return ::flatbuffers::EndianScalar(octet3_);
  }
  uint8_t octet4() const {
    return ::flatbuffers::EndianScalar(octet4_);
  }
};
FLATBUFFERS_STRUCT_END(kIpAddr, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) kIpv6Addr FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t value_[24];

 public:
  kIpv6Addr()
      : value_() {
  }
  kIpv6Addr(::flatbuffers::span<const uint8_t, 24> _value) {
    ::flatbuffers::CastToArray(value_).CopyFromSpan(_value);
  }
  const ::flatbuffers::Array<uint8_t, 24> *value() const {
    return &::flatbuffers::CastToArray(value_);
  }
};
FLATBUFFERS_STRUCT_END(kIpv6Addr, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) kEui48 FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t value_[3];

 public:
  kEui48()
      : value_() {
  }
  kEui48(::flatbuffers::span<const uint8_t, 3> _value) {
    ::flatbuffers::CastToArray(value_).CopyFromSpan(_value);
  }
  const ::flatbuffers::Array<uint8_t, 3> *value() const {
    return &::flatbuffers::CastToArray(value_);
  }
};
FLATBUFFERS_STRUCT_END(kEui48, 3);

struct kStringx FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef kStringxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct kStringxBuilder {
  typedef kStringx Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(kStringx::VT_VALUE, value);
  }
  explicit kStringxBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<kStringx> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<kStringx>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<kStringx> CreatekStringx(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  kStringxBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<kStringx> CreatekStringxDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return CreatekStringx(
      _fbb,
      value__);
}

struct SunspecPointDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecPointDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DATA_TYPE = 6,
    VT_DATA = 8,
    VT_COUNT = 10,
    VT_COUNT_POINT_ID = 12,
    VT_SIZE = 14,
    VT_SF = 16,
    VT_SF_ID = 18,
    VT_UNITS = 20,
    VT_ACCESS = 22,
    VT_MANDATORY = 24,
    VT_LABEL = 26
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  SunspecPointData data_type() const {
    return static_cast<SunspecPointData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const kSint16 *data_as_kSint16() const {
    return data_type() == SunspecPointData_kSint16 ? static_cast<const kSint16 *>(data()) : nullptr;
  }
  const kSint32 *data_as_kSint32() const {
    return data_type() == SunspecPointData_kSint32 ? static_cast<const kSint32 *>(data()) : nullptr;
  }
  const kSint64 *data_as_kSint64() const {
    return data_type() == SunspecPointData_kSint64 ? static_cast<const kSint64 *>(data()) : nullptr;
  }
  const kRaw16 *data_as_kRaw16() const {
    return data_type() == SunspecPointData_kRaw16 ? static_cast<const kRaw16 *>(data()) : nullptr;
  }
  const kUint16 *data_as_kUint16() const {
    return data_type() == SunspecPointData_kUint16 ? static_cast<const kUint16 *>(data()) : nullptr;
  }
  const kUint32 *data_as_kUint32() const {
    return data_type() == SunspecPointData_kUint32 ? static_cast<const kUint32 *>(data()) : nullptr;
  }
  const kUint64 *data_as_kUint64() const {
    return data_type() == SunspecPointData_kUint64 ? static_cast<const kUint64 *>(data()) : nullptr;
  }
  const kAcc16 *data_as_kAcc16() const {
    return data_type() == SunspecPointData_kAcc16 ? static_cast<const kAcc16 *>(data()) : nullptr;
  }
  const KAcc32 *data_as_KAcc32() const {
    return data_type() == SunspecPointData_KAcc32 ? static_cast<const KAcc32 *>(data()) : nullptr;
  }
  const kAcc64 *data_as_kAcc64() const {
    return data_type() == SunspecPointData_kAcc64 ? static_cast<const kAcc64 *>(data()) : nullptr;
  }
  const kBitfield16 *data_as_kBitfield16() const {
    return data_type() == SunspecPointData_kBitfield16 ? static_cast<const kBitfield16 *>(data()) : nullptr;
  }
  const kBitfield32 *data_as_kBitfield32() const {
    return data_type() == SunspecPointData_kBitfield32 ? static_cast<const kBitfield32 *>(data()) : nullptr;
  }
  const kBitfield64 *data_as_kBitfield64() const {
    return data_type() == SunspecPointData_kBitfield64 ? static_cast<const kBitfield64 *>(data()) : nullptr;
  }
  const kEnum16 *data_as_kEnum16() const {
    return data_type() == SunspecPointData_kEnum16 ? static_cast<const kEnum16 *>(data()) : nullptr;
  }
  const kEnum32 *data_as_kEnum32() const {
    return data_type() == SunspecPointData_kEnum32 ? static_cast<const kEnum32 *>(data()) : nullptr;
  }
  const kFloat32 *data_as_kFloat32() const {
    return data_type() == SunspecPointData_kFloat32 ? static_cast<const kFloat32 *>(data()) : nullptr;
  }
  const kFloat64 *data_as_kFloat64() const {
    return data_type() == SunspecPointData_kFloat64 ? static_cast<const kFloat64 *>(data()) : nullptr;
  }
  const kStringx *data_as_kStringx() const {
    return data_type() == SunspecPointData_kStringx ? static_cast<const kStringx *>(data()) : nullptr;
  }
  const kSunsSf *data_as_kSunsSf() const {
    return data_type() == SunspecPointData_kSunsSf ? static_cast<const kSunsSf *>(data()) : nullptr;
  }
  const kPad16 *data_as_kPad16() const {
    return data_type() == SunspecPointData_kPad16 ? static_cast<const kPad16 *>(data()) : nullptr;
  }
  const kIpAddr *data_as_kIpAddr() const {
    return data_type() == SunspecPointData_kIpAddr ? static_cast<const kIpAddr *>(data()) : nullptr;
  }
  const kIpv6Addr *data_as_kIpv6Addr() const {
    return data_type() == SunspecPointData_kIpv6Addr ? static_cast<const kIpv6Addr *>(data()) : nullptr;
  }
  const kEui48 *data_as_kEui48() const {
    return data_type() == SunspecPointData_kEui48 ? static_cast<const kEui48 *>(data()) : nullptr;
  }
  uint16_t count() const {
    return GetField<uint16_t>(VT_COUNT, 1);
  }
  const ::flatbuffers::String *count_point_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNT_POINT_ID);
  }
  uint16_t size() const {
    return GetField<uint16_t>(VT_SIZE, 0);
  }
  int16_t sf() const {
    return GetField<int16_t>(VT_SF, 0);
  }
  const ::flatbuffers::String *sf_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SF_ID);
  }
  const ::flatbuffers::String *units() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UNITS);
  }
  SunspecPointAccessType access() const {
    return static_cast<SunspecPointAccessType>(GetField<uint8_t>(VT_ACCESS, 0));
  }
  SunspecPointMandatoryType mandatory() const {
    return static_cast<SunspecPointMandatoryType>(GetField<uint8_t>(VT_MANDATORY, 1));
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifySunspecPointData(verifier, data(), data_type()) &&
           VerifyField<uint16_t>(verifier, VT_COUNT, 2) &&
           VerifyOffset(verifier, VT_COUNT_POINT_ID) &&
           verifier.VerifyString(count_point_id()) &&
           VerifyField<uint16_t>(verifier, VT_SIZE, 2) &&
           VerifyField<int16_t>(verifier, VT_SF, 2) &&
           VerifyOffset(verifier, VT_SF_ID) &&
           verifier.VerifyString(sf_id()) &&
           VerifyOffset(verifier, VT_UNITS) &&
           verifier.VerifyString(units()) &&
           VerifyField<uint8_t>(verifier, VT_ACCESS, 1) &&
           VerifyField<uint8_t>(verifier, VT_MANDATORY, 1) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           verifier.EndTable();
  }
};

template<> inline const kSint16 *SunspecPointDef::data_as<kSint16>() const {
  return data_as_kSint16();
}

template<> inline const kSint32 *SunspecPointDef::data_as<kSint32>() const {
  return data_as_kSint32();
}

template<> inline const kSint64 *SunspecPointDef::data_as<kSint64>() const {
  return data_as_kSint64();
}

template<> inline const kRaw16 *SunspecPointDef::data_as<kRaw16>() const {
  return data_as_kRaw16();
}

template<> inline const kUint16 *SunspecPointDef::data_as<kUint16>() const {
  return data_as_kUint16();
}

template<> inline const kUint32 *SunspecPointDef::data_as<kUint32>() const {
  return data_as_kUint32();
}

template<> inline const kUint64 *SunspecPointDef::data_as<kUint64>() const {
  return data_as_kUint64();
}

template<> inline const kAcc16 *SunspecPointDef::data_as<kAcc16>() const {
  return data_as_kAcc16();
}

template<> inline const KAcc32 *SunspecPointDef::data_as<KAcc32>() const {
  return data_as_KAcc32();
}

template<> inline const kAcc64 *SunspecPointDef::data_as<kAcc64>() const {
  return data_as_kAcc64();
}

template<> inline const kBitfield16 *SunspecPointDef::data_as<kBitfield16>() const {
  return data_as_kBitfield16();
}

template<> inline const kBitfield32 *SunspecPointDef::data_as<kBitfield32>() const {
  return data_as_kBitfield32();
}

template<> inline const kBitfield64 *SunspecPointDef::data_as<kBitfield64>() const {
  return data_as_kBitfield64();
}

template<> inline const kEnum16 *SunspecPointDef::data_as<kEnum16>() const {
  return data_as_kEnum16();
}

template<> inline const kEnum32 *SunspecPointDef::data_as<kEnum32>() const {
  return data_as_kEnum32();
}

template<> inline const kFloat32 *SunspecPointDef::data_as<kFloat32>() const {
  return data_as_kFloat32();
}

template<> inline const kFloat64 *SunspecPointDef::data_as<kFloat64>() const {
  return data_as_kFloat64();
}

template<> inline const kStringx *SunspecPointDef::data_as<kStringx>() const {
  return data_as_kStringx();
}

template<> inline const kSunsSf *SunspecPointDef::data_as<kSunsSf>() const {
  return data_as_kSunsSf();
}

template<> inline const kPad16 *SunspecPointDef::data_as<kPad16>() const {
  return data_as_kPad16();
}

template<> inline const kIpAddr *SunspecPointDef::data_as<kIpAddr>() const {
  return data_as_kIpAddr();
}

template<> inline const kIpv6Addr *SunspecPointDef::data_as<kIpv6Addr>() const {
  return data_as_kIpv6Addr();
}

template<> inline const kEui48 *SunspecPointDef::data_as<kEui48>() const {
  return data_as_kEui48();
}

struct SunspecPointDefBuilder {
  typedef SunspecPointDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(SunspecPointDef::VT_ID, id);
  }
  void add_data_type(SunspecPointData data_type) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(SunspecPointDef::VT_DATA, data);
  }
  void add_count(uint16_t count) {
    fbb_.AddElement<uint16_t>(SunspecPointDef::VT_COUNT, count, 1);
  }
  void add_count_point_id(::flatbuffers::Offset<::flatbuffers::String> count_point_id) {
    fbb_.AddOffset(SunspecPointDef::VT_COUNT_POINT_ID, count_point_id);
  }
  void add_size(uint16_t size) {
    fbb_.AddElement<uint16_t>(SunspecPointDef::VT_SIZE, size, 0);
  }
  void add_sf(int16_t sf) {
    fbb_.AddElement<int16_t>(SunspecPointDef::VT_SF, sf, 0);
  }
  void add_sf_id(::flatbuffers::Offset<::flatbuffers::String> sf_id) {
    fbb_.AddOffset(SunspecPointDef::VT_SF_ID, sf_id);
  }
  void add_units(::flatbuffers::Offset<::flatbuffers::String> units) {
    fbb_.AddOffset(SunspecPointDef::VT_UNITS, units);
  }
  void add_access(SunspecPointAccessType access) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_ACCESS, static_cast<uint8_t>(access), 0);
  }
  void add_mandatory(SunspecPointMandatoryType mandatory) {
    fbb_.AddElement<uint8_t>(SunspecPointDef::VT_MANDATORY, static_cast<uint8_t>(mandatory), 1);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(SunspecPointDef::VT_LABEL, label);
  }
  explicit SunspecPointDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecPointDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecPointDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecPointDef> CreateSunspecPointDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    SunspecPointData data_type = SunspecPointData_NONE,
    ::flatbuffers::Offset<void> data = 0,
    uint16_t count = 1,
    ::flatbuffers::Offset<::flatbuffers::String> count_point_id = 0,
    uint16_t size = 0,
    int16_t sf = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sf_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> units = 0,
    SunspecPointAccessType access = SunspecPointAccessType_kR,
    SunspecPointMandatoryType mandatory = SunspecPointMandatoryType_kO,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0) {
  SunspecPointDefBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_units(units);
  builder_.add_sf_id(sf_id);
  builder_.add_count_point_id(count_point_id);
  builder_.add_data(data);
  builder_.add_id(id);
  builder_.add_sf(sf);
  builder_.add_size(size);
  builder_.add_count(count);
  builder_.add_mandatory(mandatory);
  builder_.add_access(access);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SunspecPointDef> CreateSunspecPointDefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    SunspecPointData data_type = SunspecPointData_NONE,
    ::flatbuffers::Offset<void> data = 0,
    uint16_t count = 1,
    const char *count_point_id = nullptr,
    uint16_t size = 0,
    int16_t sf = 0,
    const char *sf_id = nullptr,
    const char *units = nullptr,
    SunspecPointAccessType access = SunspecPointAccessType_kR,
    SunspecPointMandatoryType mandatory = SunspecPointMandatoryType_kO,
    const char *label = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto count_point_id__ = count_point_id ? _fbb.CreateString(count_point_id) : 0;
  auto sf_id__ = sf_id ? _fbb.CreateString(sf_id) : 0;
  auto units__ = units ? _fbb.CreateString(units) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return CreateSunspecPointDef(
      _fbb,
      id__,
      data_type,
      data,
      count,
      count_point_id__,
      size,
      sf,
      sf_id__,
      units__,
      access,
      mandatory,
      label__);
}

struct SunspecGroupDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecGroupDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_COUNT = 8,
    VT_COUNT_POINT_ID = 10,
    VT_POINTS = 12,
    VT_GROUPS = 14,
    VT_LABEL = 16
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  SunspecGroupType type() const {
    return static_cast<SunspecGroupType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  uint16_t count() const {
    return GetField<uint16_t>(VT_COUNT, 1);
  }
  const ::flatbuffers::String *count_point_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNT_POINT_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>> *points() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>> *>(VT_POINTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>> *groups() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>> *>(VT_GROUPS);
  }
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint16_t>(verifier, VT_COUNT, 2) &&
           VerifyOffset(verifier, VT_COUNT_POINT_ID) &&
           verifier.VerifyString(count_point_id()) &&
           VerifyOffset(verifier, VT_POINTS) &&
           verifier.VerifyVector(points()) &&
           verifier.VerifyVectorOfTables(points()) &&
           VerifyOffset(verifier, VT_GROUPS) &&
           verifier.VerifyVector(groups()) &&
           verifier.VerifyVectorOfTables(groups()) &&
           VerifyOffset(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           verifier.EndTable();
  }
};

struct SunspecGroupDefBuilder {
  typedef SunspecGroupDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(SunspecGroupDef::VT_ID, id);
  }
  void add_type(SunspecGroupType type) {
    fbb_.AddElement<uint8_t>(SunspecGroupDef::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_count(uint16_t count) {
    fbb_.AddElement<uint16_t>(SunspecGroupDef::VT_COUNT, count, 1);
  }
  void add_count_point_id(::flatbuffers::Offset<::flatbuffers::String> count_point_id) {
    fbb_.AddOffset(SunspecGroupDef::VT_COUNT_POINT_ID, count_point_id);
  }
  void add_points(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>>> points) {
    fbb_.AddOffset(SunspecGroupDef::VT_POINTS, points);
  }
  void add_groups(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>>> groups) {
    fbb_.AddOffset(SunspecGroupDef::VT_GROUPS, groups);
  }
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(SunspecGroupDef::VT_LABEL, label);
  }
  explicit SunspecGroupDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecGroupDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecGroupDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecGroupDef> CreateSunspecGroupDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    SunspecGroupType type = SunspecGroupType_kGroup,
    uint16_t count = 1,
    ::flatbuffers::Offset<::flatbuffers::String> count_point_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecPointDef>>> points = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SunspecGroupDef>>> groups = 0,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0) {
  SunspecGroupDefBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_groups(groups);
  builder_.add_points(points);
  builder_.add_count_point_id(count_point_id);
  builder_.add_id(id);
  builder_.add_count(count);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SunspecGroupDef> CreateSunspecGroupDefDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    SunspecGroupType type = SunspecGroupType_kGroup,
    uint16_t count = 1,
    const char *count_point_id = nullptr,
    const std::vector<::flatbuffers::Offset<SunspecPointDef>> *points = nullptr,
    const std::vector<::flatbuffers::Offset<SunspecGroupDef>> *groups = nullptr,
    const char *label = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto count_point_id__ = count_point_id ? _fbb.CreateString(count_point_id) : 0;
  auto points__ = points ? _fbb.CreateVector<::flatbuffers::Offset<SunspecPointDef>>(*points) : 0;
  auto groups__ = groups ? _fbb.CreateVector<::flatbuffers::Offset<SunspecGroupDef>>(*groups) : 0;
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return CreateSunspecGroupDef(
      _fbb,
      id__,
      type,
      count,
      count_point_id__,
      points__,
      groups__,
      label__);
}

struct SunspecModelDef FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunspecModelDefBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_GROUP = 6
  };
  SunspecModelList id() const {
    return static_cast<SunspecModelList>(GetField<uint16_t>(VT_ID, 0));
  }
  const SunspecGroupDef *group() const {
    return GetPointer<const SunspecGroupDef *>(VT_GROUP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ID, 2) &&
           VerifyOffset(verifier, VT_GROUP) &&
           verifier.VerifyTable(group()) &&
           verifier.EndTable();
  }
};

struct SunspecModelDefBuilder {
  typedef SunspecModelDef Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(SunspecModelList id) {
    fbb_.AddElement<uint16_t>(SunspecModelDef::VT_ID, static_cast<uint16_t>(id), 0);
  }
  void add_group(::flatbuffers::Offset<SunspecGroupDef> group) {
    fbb_.AddOffset(SunspecModelDef::VT_GROUP, group);
  }
  explicit SunspecModelDefBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SunspecModelDef> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SunspecModelDef>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SunspecModelDef> CreateSunspecModelDef(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    SunspecModelList id = SunspecModelList_KModelInvalid,
    ::flatbuffers::Offset<SunspecGroupDef> group = 0) {
  SunspecModelDefBuilder builder_(_fbb);
  builder_.add_group(group);
  builder_.add_id(id);
  return builder_.Finish();
}

inline bool VerifySunspecPointData(::flatbuffers::Verifier &verifier, const void *obj, SunspecPointData type) {
  switch (type) {
    case SunspecPointData_NONE: {
      return true;
    }
    case SunspecPointData_kSint16: {
      return verifier.VerifyField<kSint16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_kSint32: {
      return verifier.VerifyField<kSint32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_kSint64: {
      return verifier.VerifyField<kSint64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_kRaw16: {
      return verifier.VerifyField<kRaw16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_kUint16: {
      return verifier.VerifyField<kUint16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_kUint32: {
      return verifier.VerifyField<kUint32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_kUint64: {
      return verifier.VerifyField<kUint64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_kAcc16: {
      return verifier.VerifyField<kAcc16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_KAcc32: {
      return verifier.VerifyField<KAcc32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_kAcc64: {
      return verifier.VerifyField<kAcc64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_kBitfield16: {
      return verifier.VerifyField<kBitfield16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_kBitfield32: {
      return verifier.VerifyField<kBitfield32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_kBitfield64: {
      return verifier.VerifyField<kBitfield64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_kEnum16: {
      return verifier.VerifyField<kEnum16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_kEnum32: {
      return verifier.VerifyField<kEnum32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_kFloat32: {
      return verifier.VerifyField<kFloat32>(static_cast<const uint8_t *>(obj), 0, 4);
    }
    case SunspecPointData_kFloat64: {
      return verifier.VerifyField<kFloat64>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case SunspecPointData_kStringx: {
      auto ptr = reinterpret_cast<const kStringx *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SunspecPointData_kSunsSf: {
      return verifier.VerifyField<kSunsSf>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_kPad16: {
      return verifier.VerifyField<kPad16>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case SunspecPointData_kIpAddr: {
      return verifier.VerifyField<kIpAddr>(static_cast<const uint8_t *>(obj), 0, 1);
    }
    case SunspecPointData_kIpv6Addr: {
      return verifier.VerifyField<kIpv6Addr>(static_cast<const uint8_t *>(obj), 0, 1);
    }
    case SunspecPointData_kEui48: {
      return verifier.VerifyField<kEui48>(static_cast<const uint8_t *>(obj), 0, 1);
    }
    default: return true;
  }
}

inline bool VerifySunspecPointDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySunspecPointData(
        verifier,  values->Get(i), types->GetEnum<SunspecPointData>(i))) {
      return false;
    }
  }
  return true;
}

inline const SunspecModelDef *GetSunspecModelDef(const void *buf) {
  return ::flatbuffers::GetRoot<SunspecModelDef>(buf);
}

inline const SunspecModelDef *GetSizePrefixedSunspecModelDef(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<SunspecModelDef>(buf);
}

inline bool VerifySunspecModelDefBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SunspecModelDef>(nullptr);
}

inline bool VerifySizePrefixedSunspecModelDefBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SunspecModelDef>(nullptr);
}

inline void FinishSunspecModelDefBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SunspecModelDef> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSunspecModelDefBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<SunspecModelDef> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_SUNSPECMODELDEFINITION_H_
