/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "sunspec_model_definition.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Sint16, Sint16, AUTO)


PB_BIND(Sint32, Sint32, AUTO)


PB_BIND(Sint64, Sint64, AUTO)


PB_BIND(Uint16, Uint16, AUTO)


PB_BIND(Uint32, Uint32, AUTO)


PB_BIND(Uint64, Uint64, AUTO)


PB_BIND(Raw16, Raw16, AUTO)


PB_BIND(Acc16, Acc16, AUTO)


PB_BIND(Acc32, Acc32, AUTO)


PB_BIND(Acc64, Acc64, AUTO)


PB_BIND(Bitfield16, Bitfield16, AUTO)


PB_BIND(Bitfield32, Bitfield32, AUTO)


PB_BIND(Bitfield64, Bitfield64, AUTO)


PB_BIND(Enum16, Enum16, AUTO)


PB_BIND(Enum32, Enum32, AUTO)


PB_BIND(Float32, Float32, AUTO)


PB_BIND(Float64, Float64, AUTO)


PB_BIND(Stringx, Stringx, AUTO)


PB_BIND(SunsSf, SunsSf, AUTO)


PB_BIND(Pad16, Pad16, AUTO)


PB_BIND(IpAddr, IpAddr, AUTO)


PB_BIND(Ipv6Addr, Ipv6Addr, AUTO)


PB_BIND(Eui48, Eui48, AUTO)


PB_BIND(SunspecPointData, SunspecPointData, AUTO)


PB_BIND(SunspecPointDef, SunspecPointDef, AUTO)


PB_BIND(SunspecGroupDef, SunspecGroupDef, AUTO)


PB_BIND(SunspecModelDef, SunspecModelDef, AUTO)









#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

