/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SUNSPEC_MODEL_DEFINITION_PB_H_INCLUDED
#define PB_SUNSPEC_MODEL_DEFINITION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SunspecPointAccess {
    SunspecPointAccess_kR = 0, /* Read-only */
    SunspecPointAccess_kRW = 1 /* Read-write */
} SunspecPointAccess;

typedef enum _SunspecPointMandatory {
    SunspecPointMandatory_kM = 0, /* Optional */
    SunspecPointMandatory_kO = 1 /* Mandatory */
} SunspecPointMandatory;

typedef enum _SunspecGroupType {
    SunspecGroupType_kGroup = 0,
    SunspecGroupType_kSync = 1
} SunspecGroupType;

/* Struct definitions */
typedef struct _Sint16 {
    int32_t value;
} Sint16;

typedef struct _Sint32 {
    int32_t value;
} Sint32;

typedef struct _Sint64 {
    int64_t value;
} Sint64;

typedef struct _Uint16 {
    uint32_t value;
} Uint16;

typedef struct _Uint32 {
    uint32_t value;
} Uint32;

typedef struct _Uint64 {
    uint64_t value;
} Uint64;

typedef struct _Raw16 {
    uint32_t value;
} Raw16;

typedef struct _Acc16 {
    uint32_t value;
} Acc16;

typedef struct _Acc32 {
    uint32_t value;
} Acc32;

typedef struct _Acc64 {
    uint64_t value;
} Acc64;

typedef struct _Bitfield16 {
    uint32_t value;
} Bitfield16;

typedef struct _Bitfield32 {
    uint32_t value;
} Bitfield32;

typedef struct _Bitfield64 {
    uint64_t value;
} Bitfield64;

typedef struct _Enum16 {
    uint32_t value;
} Enum16;

typedef struct _Enum32 {
    uint32_t value;
} Enum32;

typedef struct _Float32 {
    float value;
} Float32;

typedef struct _Float64 {
    double value;
} Float64;

typedef struct _Stringx {
    pb_callback_t value;
} Stringx;

typedef struct _SunsSf {
    int32_t value;
} SunsSf;

typedef struct _Pad16 {
    uint32_t value;
} Pad16;

typedef struct _IpAddr {
    uint32_t octet1;
    uint32_t octet2;
    uint32_t octet3;
    uint32_t octet4;
} IpAddr;

typedef struct _Ipv6Addr {
    pb_callback_t value; /* exactly 16 bytes */
} Ipv6Addr;

typedef struct _Eui48 {
    pb_callback_t value; /* exactly 6 bytes */
} Eui48;

typedef struct _SunspecPointData {
    pb_size_t which_kind;
    union _SunspecPointData_kind {
        Sint16 Sint16;
        Sint32 Sint32;
        Sint64 Sint64;
        Raw16 Raw16;
        Uint16 Uint16;
        Uint32 Uint32;
        Uint64 Uint64;
        Acc16 Acc16;
        Acc32 Acc32;
        Acc64 Acc64;
        Bitfield16 Bitfield16;
        Bitfield32 Bitfield32;
        Bitfield64 Bitfield64;
        Enum16 Enum16;
        Enum32 Enum32;
        Float32 Float32;
        Float64 Float64;
        Stringx Stringx;
        SunsSf SunsSf;
        Pad16 Pad16;
        IpAddr IpAddr;
        Ipv6Addr Ipv6Addr;
        Eui48 Eui48;
    } kind;
} SunspecPointData;

typedef struct _SunspecPointDef {
    pb_callback_t id;
    bool has_data;
    SunspecPointData data;
    uint32_t count; /* default = 1 */
    pb_callback_t count_point_id;
    uint32_t size;
    int32_t sf; /* scale factor */
    pb_callback_t sf_id;
    pb_callback_t units;
    SunspecPointAccess access;
    SunspecPointMandatory mandatory;
    pb_callback_t label;
} SunspecPointDef;

typedef struct _SunspecGroupDef {
    pb_callback_t id;
    SunspecGroupType type;
    uint32_t count;
    pb_callback_t count_point_id;
    pb_callback_t points;
    pb_callback_t groups;
    pb_callback_t label;
} SunspecGroupDef;

typedef struct _SunspecModelDef {
    uint32_t id; /* uint16 stored as uint32 */
    bool has_group;
    SunspecGroupDef group;
} SunspecModelDef;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SunspecPointAccess_MIN SunspecPointAccess_kR
#define _SunspecPointAccess_MAX SunspecPointAccess_kRW
#define _SunspecPointAccess_ARRAYSIZE ((SunspecPointAccess)(SunspecPointAccess_kRW+1))

#define _SunspecPointMandatory_MIN SunspecPointMandatory_kM
#define _SunspecPointMandatory_MAX SunspecPointMandatory_kO
#define _SunspecPointMandatory_ARRAYSIZE ((SunspecPointMandatory)(SunspecPointMandatory_kO+1))

#define _SunspecGroupType_MIN SunspecGroupType_kGroup
#define _SunspecGroupType_MAX SunspecGroupType_kSync
#define _SunspecGroupType_ARRAYSIZE ((SunspecGroupType)(SunspecGroupType_kSync+1))

























#define SunspecPointDef_access_ENUMTYPE SunspecPointAccess
#define SunspecPointDef_mandatory_ENUMTYPE SunspecPointMandatory

#define SunspecGroupDef_type_ENUMTYPE SunspecGroupType



/* Initializer values for message structs */
#define Sint16_init_default                      {0}
#define Sint32_init_default                      {0}
#define Sint64_init_default                      {0}
#define Uint16_init_default                      {0}
#define Uint32_init_default                      {0}
#define Uint64_init_default                      {0}
#define Raw16_init_default                       {0}
#define Acc16_init_default                       {0}
#define Acc32_init_default                       {0}
#define Acc64_init_default                       {0}
#define Bitfield16_init_default                  {0}
#define Bitfield32_init_default                  {0}
#define Bitfield64_init_default                  {0}
#define Enum16_init_default                      {0}
#define Enum32_init_default                      {0}
#define Float32_init_default                     {0}
#define Float64_init_default                     {0}
#define Stringx_init_default                     {{{NULL}, NULL}}
#define SunsSf_init_default                      {0}
#define Pad16_init_default                       {0}
#define IpAddr_init_default                      {0, 0, 0, 0}
#define Ipv6Addr_init_default                    {{{NULL}, NULL}}
#define Eui48_init_default                       {{{NULL}, NULL}}
#define SunspecPointData_init_default            {0, {Sint16_init_default}}
#define SunspecPointDef_init_default             {{{NULL}, NULL}, false, SunspecPointData_init_default, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, _SunspecPointAccess_MIN, _SunspecPointMandatory_MIN, {{NULL}, NULL}}
#define SunspecGroupDef_init_default             {{{NULL}, NULL}, _SunspecGroupType_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SunspecModelDef_init_default             {0, false, SunspecGroupDef_init_default}
#define Sint16_init_zero                         {0}
#define Sint32_init_zero                         {0}
#define Sint64_init_zero                         {0}
#define Uint16_init_zero                         {0}
#define Uint32_init_zero                         {0}
#define Uint64_init_zero                         {0}
#define Raw16_init_zero                          {0}
#define Acc16_init_zero                          {0}
#define Acc32_init_zero                          {0}
#define Acc64_init_zero                          {0}
#define Bitfield16_init_zero                     {0}
#define Bitfield32_init_zero                     {0}
#define Bitfield64_init_zero                     {0}
#define Enum16_init_zero                         {0}
#define Enum32_init_zero                         {0}
#define Float32_init_zero                        {0}
#define Float64_init_zero                        {0}
#define Stringx_init_zero                        {{{NULL}, NULL}}
#define SunsSf_init_zero                         {0}
#define Pad16_init_zero                          {0}
#define IpAddr_init_zero                         {0, 0, 0, 0}
#define Ipv6Addr_init_zero                       {{{NULL}, NULL}}
#define Eui48_init_zero                          {{{NULL}, NULL}}
#define SunspecPointData_init_zero               {0, {Sint16_init_zero}}
#define SunspecPointDef_init_zero                {{{NULL}, NULL}, false, SunspecPointData_init_zero, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, _SunspecPointAccess_MIN, _SunspecPointMandatory_MIN, {{NULL}, NULL}}
#define SunspecGroupDef_init_zero                {{{NULL}, NULL}, _SunspecGroupType_MIN, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SunspecModelDef_init_zero                {0, false, SunspecGroupDef_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Sint16_value_tag                         1
#define Sint32_value_tag                         1
#define Sint64_value_tag                         1
#define Uint16_value_tag                         1
#define Uint32_value_tag                         1
#define Uint64_value_tag                         1
#define Raw16_value_tag                          1
#define Acc16_value_tag                          1
#define Acc32_value_tag                          1
#define Acc64_value_tag                          1
#define Bitfield16_value_tag                     1
#define Bitfield32_value_tag                     1
#define Bitfield64_value_tag                     1
#define Enum16_value_tag                         1
#define Enum32_value_tag                         1
#define Float32_value_tag                        1
#define Float64_value_tag                        1
#define Stringx_value_tag                        1
#define SunsSf_value_tag                         1
#define Pad16_value_tag                          1
#define IpAddr_octet1_tag                        1
#define IpAddr_octet2_tag                        2
#define IpAddr_octet3_tag                        3
#define IpAddr_octet4_tag                        4
#define Ipv6Addr_value_tag                       1
#define Eui48_value_tag                          1
#define SunspecPointData_Sint16_tag              1
#define SunspecPointData_Sint32_tag              2
#define SunspecPointData_Sint64_tag              3
#define SunspecPointData_Raw16_tag               4
#define SunspecPointData_Uint16_tag              5
#define SunspecPointData_Uint32_tag              6
#define SunspecPointData_Uint64_tag              7
#define SunspecPointData_Acc16_tag               8
#define SunspecPointData_Acc32_tag               9
#define SunspecPointData_Acc64_tag               10
#define SunspecPointData_Bitfield16_tag          11
#define SunspecPointData_Bitfield32_tag          12
#define SunspecPointData_Bitfield64_tag          13
#define SunspecPointData_Enum16_tag              14
#define SunspecPointData_Enum32_tag              15
#define SunspecPointData_Float32_tag             16
#define SunspecPointData_Float64_tag             17
#define SunspecPointData_Stringx_tag             18
#define SunspecPointData_SunsSf_tag              19
#define SunspecPointData_Pad16_tag               20
#define SunspecPointData_IpAddr_tag              21
#define SunspecPointData_Ipv6Addr_tag            22
#define SunspecPointData_Eui48_tag               23
#define SunspecPointDef_id_tag                   1
#define SunspecPointDef_data_tag                 2
#define SunspecPointDef_count_tag                3
#define SunspecPointDef_count_point_id_tag       4
#define SunspecPointDef_size_tag                 5
#define SunspecPointDef_sf_tag                   6
#define SunspecPointDef_sf_id_tag                7
#define SunspecPointDef_units_tag                8
#define SunspecPointDef_access_tag               9
#define SunspecPointDef_mandatory_tag            10
#define SunspecPointDef_label_tag                11
#define SunspecGroupDef_id_tag                   1
#define SunspecGroupDef_type_tag                 2
#define SunspecGroupDef_count_tag                3
#define SunspecGroupDef_count_point_id_tag       4
#define SunspecGroupDef_points_tag               5
#define SunspecGroupDef_groups_tag               6
#define SunspecGroupDef_label_tag                7
#define SunspecModelDef_id_tag                   1
#define SunspecModelDef_group_tag                2

/* Struct field encoding specification for nanopb */
#define Sint16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1)
#define Sint16_CALLBACK NULL
#define Sint16_DEFAULT NULL

#define Sint32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1)
#define Sint32_CALLBACK NULL
#define Sint32_DEFAULT NULL

#define Sint64_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    value,             1)
#define Sint64_CALLBACK NULL
#define Sint64_DEFAULT NULL

#define Uint16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Uint16_CALLBACK NULL
#define Uint16_DEFAULT NULL

#define Uint32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Uint32_CALLBACK NULL
#define Uint32_DEFAULT NULL

#define Uint64_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   value,             1)
#define Uint64_CALLBACK NULL
#define Uint64_DEFAULT NULL

#define Raw16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Raw16_CALLBACK NULL
#define Raw16_DEFAULT NULL

#define Acc16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Acc16_CALLBACK NULL
#define Acc16_DEFAULT NULL

#define Acc32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Acc32_CALLBACK NULL
#define Acc32_DEFAULT NULL

#define Acc64_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   value,             1)
#define Acc64_CALLBACK NULL
#define Acc64_DEFAULT NULL

#define Bitfield16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Bitfield16_CALLBACK NULL
#define Bitfield16_DEFAULT NULL

#define Bitfield32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Bitfield32_CALLBACK NULL
#define Bitfield32_DEFAULT NULL

#define Bitfield64_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   value,             1)
#define Bitfield64_CALLBACK NULL
#define Bitfield64_DEFAULT NULL

#define Enum16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Enum16_CALLBACK NULL
#define Enum16_DEFAULT NULL

#define Enum32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Enum32_CALLBACK NULL
#define Enum32_DEFAULT NULL

#define Float32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             1)
#define Float32_CALLBACK NULL
#define Float32_DEFAULT NULL

#define Float64_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1)
#define Float64_CALLBACK NULL
#define Float64_DEFAULT NULL

#define Stringx_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   value,             1)
#define Stringx_CALLBACK pb_default_field_callback
#define Stringx_DEFAULT NULL

#define SunsSf_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    value,             1)
#define SunsSf_CALLBACK NULL
#define SunsSf_DEFAULT NULL

#define Pad16_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define Pad16_CALLBACK NULL
#define Pad16_DEFAULT NULL

#define IpAddr_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   octet1,            1) \
X(a, STATIC,   SINGULAR, UINT32,   octet2,            2) \
X(a, STATIC,   SINGULAR, UINT32,   octet3,            3) \
X(a, STATIC,   SINGULAR, UINT32,   octet4,            4)
#define IpAddr_CALLBACK NULL
#define IpAddr_DEFAULT NULL

#define Ipv6Addr_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             1)
#define Ipv6Addr_CALLBACK pb_default_field_callback
#define Ipv6Addr_DEFAULT NULL

#define Eui48_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             1)
#define Eui48_CALLBACK pb_default_field_callback
#define Eui48_DEFAULT NULL

#define SunspecPointData_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Sint16,kind.Sint16),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Sint32,kind.Sint32),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Sint64,kind.Sint64),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Raw16,kind.Raw16),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Uint16,kind.Uint16),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Uint32,kind.Uint32),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Uint64,kind.Uint64),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Acc16,kind.Acc16),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Acc32,kind.Acc32),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Acc64,kind.Acc64),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Bitfield16,kind.Bitfield16),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Bitfield32,kind.Bitfield32),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Bitfield64,kind.Bitfield64),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Enum16,kind.Enum16),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Enum32,kind.Enum32),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Float32,kind.Float32),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Float64,kind.Float64),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Stringx,kind.Stringx),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,SunsSf,kind.SunsSf),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Pad16,kind.Pad16),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,IpAddr,kind.IpAddr),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Ipv6Addr,kind.Ipv6Addr),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,Eui48,kind.Eui48),  23)
#define SunspecPointData_CALLBACK NULL
#define SunspecPointData_DEFAULT NULL
#define SunspecPointData_kind_Sint16_MSGTYPE Sint16
#define SunspecPointData_kind_Sint32_MSGTYPE Sint32
#define SunspecPointData_kind_Sint64_MSGTYPE Sint64
#define SunspecPointData_kind_Raw16_MSGTYPE Raw16
#define SunspecPointData_kind_Uint16_MSGTYPE Uint16
#define SunspecPointData_kind_Uint32_MSGTYPE Uint32
#define SunspecPointData_kind_Uint64_MSGTYPE Uint64
#define SunspecPointData_kind_Acc16_MSGTYPE Acc16
#define SunspecPointData_kind_Acc32_MSGTYPE Acc32
#define SunspecPointData_kind_Acc64_MSGTYPE Acc64
#define SunspecPointData_kind_Bitfield16_MSGTYPE Bitfield16
#define SunspecPointData_kind_Bitfield32_MSGTYPE Bitfield32
#define SunspecPointData_kind_Bitfield64_MSGTYPE Bitfield64
#define SunspecPointData_kind_Enum16_MSGTYPE Enum16
#define SunspecPointData_kind_Enum32_MSGTYPE Enum32
#define SunspecPointData_kind_Float32_MSGTYPE Float32
#define SunspecPointData_kind_Float64_MSGTYPE Float64
#define SunspecPointData_kind_Stringx_MSGTYPE Stringx
#define SunspecPointData_kind_SunsSf_MSGTYPE SunsSf
#define SunspecPointData_kind_Pad16_MSGTYPE Pad16
#define SunspecPointData_kind_IpAddr_MSGTYPE IpAddr
#define SunspecPointData_kind_Ipv6Addr_MSGTYPE Ipv6Addr
#define SunspecPointData_kind_Eui48_MSGTYPE Eui48

#define SunspecPointDef_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, CALLBACK, SINGULAR, STRING,   count_point_id,    4) \
X(a, STATIC,   SINGULAR, UINT32,   size,              5) \
X(a, STATIC,   SINGULAR, INT32,    sf,                6) \
X(a, CALLBACK, SINGULAR, STRING,   sf_id,             7) \
X(a, CALLBACK, SINGULAR, STRING,   units,             8) \
X(a, STATIC,   SINGULAR, UENUM,    access,            9) \
X(a, STATIC,   SINGULAR, UENUM,    mandatory,        10) \
X(a, CALLBACK, SINGULAR, STRING,   label,            11)
#define SunspecPointDef_CALLBACK pb_default_field_callback
#define SunspecPointDef_DEFAULT NULL
#define SunspecPointDef_data_MSGTYPE SunspecPointData

#define SunspecGroupDef_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   SINGULAR, UINT32,   count,             3) \
X(a, CALLBACK, SINGULAR, STRING,   count_point_id,    4) \
X(a, CALLBACK, REPEATED, MESSAGE,  points,            5) \
X(a, CALLBACK, REPEATED, MESSAGE,  groups,            6) \
X(a, CALLBACK, SINGULAR, STRING,   label,             7)
#define SunspecGroupDef_CALLBACK pb_default_field_callback
#define SunspecGroupDef_DEFAULT NULL
#define SunspecGroupDef_points_MSGTYPE SunspecPointDef
#define SunspecGroupDef_groups_MSGTYPE SunspecGroupDef

#define SunspecModelDef_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  group,             2)
#define SunspecModelDef_CALLBACK NULL
#define SunspecModelDef_DEFAULT NULL
#define SunspecModelDef_group_MSGTYPE SunspecGroupDef

extern const pb_msgdesc_t Sint16_msg;
extern const pb_msgdesc_t Sint32_msg;
extern const pb_msgdesc_t Sint64_msg;
extern const pb_msgdesc_t Uint16_msg;
extern const pb_msgdesc_t Uint32_msg;
extern const pb_msgdesc_t Uint64_msg;
extern const pb_msgdesc_t Raw16_msg;
extern const pb_msgdesc_t Acc16_msg;
extern const pb_msgdesc_t Acc32_msg;
extern const pb_msgdesc_t Acc64_msg;
extern const pb_msgdesc_t Bitfield16_msg;
extern const pb_msgdesc_t Bitfield32_msg;
extern const pb_msgdesc_t Bitfield64_msg;
extern const pb_msgdesc_t Enum16_msg;
extern const pb_msgdesc_t Enum32_msg;
extern const pb_msgdesc_t Float32_msg;
extern const pb_msgdesc_t Float64_msg;
extern const pb_msgdesc_t Stringx_msg;
extern const pb_msgdesc_t SunsSf_msg;
extern const pb_msgdesc_t Pad16_msg;
extern const pb_msgdesc_t IpAddr_msg;
extern const pb_msgdesc_t Ipv6Addr_msg;
extern const pb_msgdesc_t Eui48_msg;
extern const pb_msgdesc_t SunspecPointData_msg;
extern const pb_msgdesc_t SunspecPointDef_msg;
extern const pb_msgdesc_t SunspecGroupDef_msg;
extern const pb_msgdesc_t SunspecModelDef_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Sint16_fields &Sint16_msg
#define Sint32_fields &Sint32_msg
#define Sint64_fields &Sint64_msg
#define Uint16_fields &Uint16_msg
#define Uint32_fields &Uint32_msg
#define Uint64_fields &Uint64_msg
#define Raw16_fields &Raw16_msg
#define Acc16_fields &Acc16_msg
#define Acc32_fields &Acc32_msg
#define Acc64_fields &Acc64_msg
#define Bitfield16_fields &Bitfield16_msg
#define Bitfield32_fields &Bitfield32_msg
#define Bitfield64_fields &Bitfield64_msg
#define Enum16_fields &Enum16_msg
#define Enum32_fields &Enum32_msg
#define Float32_fields &Float32_msg
#define Float64_fields &Float64_msg
#define Stringx_fields &Stringx_msg
#define SunsSf_fields &SunsSf_msg
#define Pad16_fields &Pad16_msg
#define IpAddr_fields &IpAddr_msg
#define Ipv6Addr_fields &Ipv6Addr_msg
#define Eui48_fields &Eui48_msg
#define SunspecPointData_fields &SunspecPointData_msg
#define SunspecPointDef_fields &SunspecPointDef_msg
#define SunspecGroupDef_fields &SunspecGroupDef_msg
#define SunspecModelDef_fields &SunspecModelDef_msg

/* Maximum encoded size of messages (where known) */
/* Stringx_size depends on runtime parameters */
/* Ipv6Addr_size depends on runtime parameters */
/* Eui48_size depends on runtime parameters */
/* SunspecPointData_size depends on runtime parameters */
/* SunspecPointDef_size depends on runtime parameters */
/* SunspecGroupDef_size depends on runtime parameters */
/* SunspecModelDef_size depends on runtime parameters */
#define Acc16_size                               6
#define Acc32_size                               6
#define Acc64_size                               11
#define Bitfield16_size                          6
#define Bitfield32_size                          6
#define Bitfield64_size                          11
#define Enum16_size                              6
#define Enum32_size                              6
#define Float32_size                             5
#define Float64_size                             9
#define IpAddr_size                              24
#define Pad16_size                               6
#define Raw16_size                               6
#define SUNSPEC_MODEL_DEFINITION_PB_H_MAX_SIZE   IpAddr_size
#define Sint16_size                              11
#define Sint32_size                              11
#define Sint64_size                              11
#define SunsSf_size                              11
#define Uint16_size                              6
#define Uint32_size                              6
#define Uint64_size                              11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
