name: Test workflow

on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github action"

  say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: flatbuffer_integration
      - run: sudo apt install -y build-essential python3 cmake make ninja-build
      - run: pwd
      - run: tools/dual_target_test_build_run.sh host $(pwd) flatbuffer
